#!/usr/bin/env python3
"""Build nb19_deep_learning_instructor.ipynb — full replication of the
10_deep_learning.qmd lecture deck, with a consolidated 3Blue1Brown intuition
block and an end-to-end PyTorch FashionMNIST lab (the canonical Quickstart:
data -> model -> train -> test -> save -> load -> predict).

Run: python scripts/build_nb19.py
The student copy is generated by stripping INSTRUCTOR SOLUTION cells.
"""
import json
from pathlib import Path

IMG = ("https://raw.githubusercontent.com/davi-moreira/"
       "2026Summer_predictive_analytics_purdue_MGMT474/main/notebooks/figures/")

cells = []


def md(text):
    cells.append({"cell_type": "markdown", "metadata": {}, "source": text})


def code(text):
    cells.append({"cell_type": "code", "metadata": {}, "execution_count": None,
                  "outputs": [], "source": text})


def img(fname, width, alt="", caption=None):
    cap = f'\n<br>\n<small>{caption}</small>' if caption else ''
    a = f' alt="{alt}"' if alt else ''
    return (f'<center>\n<img src="{IMG}{fname}"{a} width="{width}"/>{cap}\n</center>')


def iframe(url, height=600):
    return (f'from IPython.display import IFrame\n'
            f'IFrame("{url}", width="100%", height={height})')


# ============================================================= HEADER
md(r"""# Special Topic — Deep Learning

<hr>

<center>
<div>
<img src="https://raw.githubusercontent.com/davi-moreira/2026Summer_predictive_analytics_purdue_MGMT474/main/notebooks/figures/mgmt_474_ai_logo_02-modified.png" width="200"/>
</div>
</center>

# <center><a class="tocSkip"></center>
# <center>QM47400 Predictive Analytics</center>
# <center>Professor: Davi Moreira </center>

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/davi-moreira/2026Summer_predictive_analytics_purdue_MGMT474/blob/main/notebooks/nb19_deep_learning_student.ipynb)""")

# ============================================================= OBJECTIVES
md(r"""## Learning Objectives

By the end of this notebook, you will be able to:

1. Explain the historical arc that took neural networks from the 1980s rebrand into deep learning's 2010 resurgence, and name the three drivers that made it work (compute, data, frameworks).
2. Compare **PyTorch** and **TensorFlow** and say which one you would reach for and why.
3. Build the right intuition for what a neural network is and how it learns, from the four foundational 3Blue1Brown chapters.
4. **Train a neural network end to end in PyTorch on the FashionMNIST dataset** — load data with `DataLoader`, define a model by subclassing `nn.Module`, run a train/test loop across epochs, **save and load** the trained weights, and **make predictions** on real images.
5. Read the math of a single hidden layer and explain how a network is fit (gradient descent, backpropagation, dropout, data augmentation).
6. Distinguish the three structural inventions — fully-connected MLPs, **convolutional networks (CNNs)** for images, and **recurrent networks (RNNs)** for sequences — and name one problem class each is designed for.
7. Decide whether deep learning is the right tool for a given business problem using a four-question rubric, and run one honest tabular comparison against gradient boosting.

> 📝 *This notebook's content is inspired by and replicates the material from [An Introduction to Statistical Learning (ISLP)](https://www.statlearning.com/) and the official [PyTorch "Learn the Basics" tutorials](https://pytorch.org/tutorials/beginner/basics/intro.html) — especially the [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html).*

> **📋 Participation Reminder:** This notebook contains **2 PAUSE-AND-DO exercises**. Complete both to receive participation credit.""")

# ============================================================= WHY THIS MATTERS
md(r"""## 💼 Why This Matters: The "What About AI?" Question Every Analyst Will Hear

The **VP of Strategy at TechCorp** sat in your Milestone 4 poster session, watched the gradient-boosting churn model demo, and asked one question:

> *"This is great. But shouldn't we be using deep learning?"*

This notebook is the answer you owe her. It does two things at once. First, it is a working analyst's **awareness module**: enough of the language and the structural ideas that you can recognize when deep learning **is** the right tool, recognize when it **is not** (most tabular business problems), and run a single fair comparison so the answer to her question is evidence-based, not vibes. Second — because awareness without hands-on contact is shallow — you will **train a real neural network end to end in PyTorch**, the same framework behind the LLMs you have used all course, and watch it learn to recognize images of clothing well enough to make correct predictions.

The plan: the history and the two big frameworks, then four short videos that build the core intuition, then the **full end-to-end PyTorch lab** on FashionMNIST. After that we go deeper — the math of a single layer, how networks are fit, the CNN and RNN inventions, and a clear-eyed "when to use deep learning" rubric.""")

md(img("10_1_1-1.png", 480, "Deep learning pioneers",
       "The 2019 ACM Turing Award honored Yann LeCun, Geoffrey Hinton, and Yoshua Bengio for the work that became modern deep learning."))

# ============================================================= OVERVIEW
md(r"""## Overview

This notebook covers, in order:

| | |
|---|---|
| 1. Deep Learning (history) | 8. Document Classification |
| 2. PyTorch vs. TensorFlow | 9. Recurrent Neural Networks — RNN |
| 3. Neural Networks — build your intuition (videos) | 10. RNN for Document Classification |
| **4. PyTorch hands-on: train on FashionMNIST end-to-end** | 11. RNN for Time Series Forecasting |
| 5. Single Layer Neural Network (the math) | 12. When to Use Deep Learning |
| 6. Fitting Neural Networks | 13. Large Language Models |
| 7. Convolutional Neural Networks — CNN | 14. Wrap-Up |

Sections 3 and 4 are the heart of the notebook: build the intuition, then train a network yourself. Section 4 is fully runnable — open it in Colab and execute the cells.""")

# ============================================================= 1. DEEP LEARNING
md(r"""# 1. Deep Learning

Neural networks have lived two lives.

**Early rise (1980s).** Neural networks first gained popularity, with high levels of excitement and dedicated conferences (NeurIPS, Snowbird).

**1990s shift.** Other methods emerged — SVMs, Random Forests, Boosting — and neural networks receded into the background.

**Resurgence (2010).** Rebranded and refined under the banner of *Deep Learning*. By the 2020s it had become extremely successful and widely adopted.

**Key drivers of success:**

1. **Compute** — rapid increases in computing power (GPUs, parallel computing). GPUs designed for video games turned out to be exactly the right hardware for the matrix multiplications a network is built from, and a \$1,000 graphics card replaced a \$100,000 cluster.
2. **Data** — the availability of large-scale labeled datasets (ImageNet, with 14 million labeled images, gave networks enough training signal to outperform every classical method).
3. **Frameworks** — user-friendly deep-learning libraries (TensorFlow, PyTorch) cut the boilerplate from thousands of lines of low-level CUDA to a few lines of Python.

Much of the credit goes to three pioneers and their research teams — **Yann LeCun**, **Geoffrey Hinton**, and **Yoshua Bengio** — who received the 2019 ACM Turing Award for their work on neural networks.

> **A question that often comes up here:** *"If the math is mostly unchanged from the 1980s, why did it take 25 years?"* Because the math was *almost* unchanged. Three small but load-bearing additions — ReLU activations replacing sigmoid (which trains better in deep networks), dropout regularization, and batch normalization — combined with the new compute and data to make training networks with hundreds of layers practical for the first time. Each addition is a "small" idea, but together they crossed the threshold.""")

md(r"""## AI Visionaries: Interviews

Three short interviews with the pioneers — worth watching once to put faces and voices to the names.

<table><tr>
<td width="33%"><center>
<iframe width="100%" height="220" src="https://www.youtube.com/embed/Ah6nR8YAYF4" title="Yann LeCun" frameborder="0" allowfullscreen></iframe>
<a href="https://www.youtube.com/watch?v=Ah6nR8YAYF4" target="_blank"><b>Yann LeCun</b><br>The Future of AI</a>
</center></td>
<td width="33%"><center>
<iframe width="100%" height="220" src="https://www.youtube.com/embed/qrvK_KuIeJk" title="Geoffrey Hinton" frameborder="0" allowfullscreen></iframe>
<a href="https://www.youtube.com/watch?v=qrvK_KuIeJk" target="_blank"><b>Geoffrey Hinton</b><br>60 Minutes Interview</a>
</center></td>
<td width="33%"><center>
<iframe width="100%" height="220" src="https://www.youtube.com/embed/5LgDUqCbBwo" title="Yoshua Bengio" frameborder="0" allowfullscreen></iframe>
<a href="https://www.youtube.com/watch?v=5LgDUqCbBwo" target="_blank"><b>Yoshua Bengio</b><br>Path to Human-Level AI</a>
</center></td>
</tr></table>""")

# ============================================================= 2. PYTORCH vs TF
md(r"""# 2. PyTorch vs. TensorFlow""")

md(img("pytorch_vs_tensorflow.png", 720, "PyTorch vs TensorFlow"))

md(r"""## What Are Deep Learning Frameworks?

Deep learning frameworks are software libraries designed to streamline the creation, training, and deployment of neural networks. They reduce boilerplate code, handle tensor operations efficiently, and make it easier to prototype and iterate on new architectures.

- They provide **pre-built functions**, **automatic differentiation**, and **GPU/TPU** support.
- **Why they are necessary:** they let researchers and developers focus on **model design** rather than low-level implementation details.

**What both give you (and why neither is just `numpy`):**

- **Tensor operations.** A tensor is a multi-dimensional array — `numpy.ndarray` is a 1- or 2-D version; tensor frameworks scale to 4-D image batches and 5-D video batches without breaking a sweat.
- **Automatic differentiation.** When you write `loss = something(weights)`, the framework remembers the chain of operations and computes `dloss/dweights` for you with one call (`loss.backward()` in PyTorch). That is the magic that makes training a network with millions of parameters tractable.
- **GPU support.** Move a tensor to the GPU with `.to('cuda')` (PyTorch) and every subsequent operation runs there. The same code on CPU "just" runs \~50× slower.
- **Pre-built layers.** Convolution, recurrence, attention — none need to be implemented from scratch.""")

md(r"""## PyTorch and TensorFlow

### What is PyTorch?

- Developed primarily by **Facebook (Meta)** and released in September 2016.
- Emphasizes a **dynamic computation graph** (eager execution).
- Highly **"Pythonic"**: feels natural for Python developers.
- Strong community presence in **academia** and research.
- Active ecosystem: **torchvision**, **torchaudio**, and more.
- Get started: <https://pytorch.org/tutorials/beginner/basics/intro.html>

### What is TensorFlow?

- Developed primarily by **Google** and released in November 2015.
- Historically used a **static graph** approach (an "eager mode" was added later).
- Comes with **extensive tools** for deployment (mobile, web, production).
- Large ecosystem with well-integrated components (**TensorBoard**, **TFX**, **TensorFlow Lite**).
- Get started: <https://www.tensorflow.org/tutorials>""")

md(r"""## Key Differences

| Aspect | **PyTorch** | **TensorFlow** |
|:---|:---|:---|
| **Computation Graph** | Dynamic graph (eager execution by default). | Historically static graph with a build-and-execute phase (now supports eager execution). |
| **Debugging & Development Style** | Straightforward for Python developers, immediate error feedback. | Trickier to debug in graph mode; eager mode helps but is newer. |
| **Deployment & Production** | TorchServe and growing enterprise support. | TensorFlow Serving, TensorFlow Lite, easy Google Cloud integration. |

## Similarities

| Similarity | Description |
|:---|:---|
| **Wide range of layers** | Convolutional, recurrent, transformers — both maintain robust libraries for standard and advanced layers. |
| **Auto-differentiation** | No need to manually compute gradients; backpropagation is handled automatically. |
| **GPU acceleration** | Both leverage CUDA (NVIDIA GPUs) or other backends to speed up training. |
| **Rich communities** | Abundant tutorials, example code, pretrained models, and Q&A forums. |""")

md(r"""## Which Should You Choose?

### Choose **PyTorch** if:

- Your focus is **rapid experimentation** and **academic research**.
- You prioritize a **Pythonic workflow** and easy debugging.
- You prefer a **dynamic graph** approach.
- You value seamless interaction with Python libraries.

### Choose **TensorFlow** if:

- You need **robust production** and **deployment pipelines**.
- You plan to integrate with **Google Cloud** services.
- You require support for **mobile/edge devices** (TensorFlow Lite).
- You want an **end-to-end ecosystem** (TFX, TensorBoard, Serving).

> **A question that often comes up here:** *"If I can only learn one, which one?"* For a working business analyst, pick **PyTorch**. Research code on GitHub, the Hugging Face model hub, and the modern LLM ecosystem are all PyTorch-first. TensorFlow is still common in production at Google-scale companies, but the gap closes every year — and the hands-on lab in this notebook is PyTorch for exactly this reason.""")

# ============================================================= 3. NN INTUITION (3B1B)
md(r"""# 3. Neural Networks — Build Your Intuition

Before you train a network, build the right mental picture of what one *is* and how it *learns*. The four videos below — 3Blue1Brown's *Deep Learning* series — are the single best visual intuition available, and they map directly onto the code you will write in Section 4. Watch them in order; together they run about an hour, and they are worth every minute.

- **Chapter 1** answers *what a neural network is* — exactly the `nn.Module` you will define.
- **Chapter 2** shows *how it learns* via gradient descent — the `optimizer.step()` in your train loop.
- **Chapters 3 & 4** open up *backpropagation* — the `loss.backward()` call that computes every gradient for you.""")

md(r"""### Chapter 1 — But what is a neural network?

The foundation: neurons, layers, weights, biases, and activations, built up on the MNIST digit-recognition problem (the cousin of the FashionMNIST problem you will solve in Section 4).

<center>
<iframe width="800" height="450" src="https://www.youtube.com/embed/aircAruvnKk" title="But what is a neural network?" frameborder="0" allowfullscreen></iframe>
<br>
<a href="https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=1" target="_blank">But what is a neural network? | Deep Learning Chapter 1</a>
</center>""")

md(r"""### Chapter 2 — Gradient descent, how neural networks learn

How a network turns "wrong answers" into "better weights": the cost function, its gradient, and the downhill step that is the entire engine of learning.

<center>
<iframe width="800" height="450" src="https://www.youtube.com/embed/IHZwWFHWa-w" title="Gradient descent, how neural networks learn" frameborder="0" allowfullscreen></iframe>
<br>
<a href="https://www.youtube.com/watch?v=IHZwWFHWa-w&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=2" target="_blank">Gradient descent, how neural networks learn | Deep Learning Chapter 2</a>
</center>""")

md(r"""### Chapter 3 — Backpropagation, intuitively

What backpropagation is really doing: how a single training example "votes" to nudge each weight up or down, and why we average those votes over a mini-batch.

<center>
<iframe width="800" height="450" src="https://www.youtube.com/embed/Ilg3gGewQ5U" title="Backpropagation, intuitively" frameborder="0" allowfullscreen></iframe>
<br>
<a href="https://www.youtube.com/watch?v=Ilg3gGewQ5U&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=3" target="_blank">Backpropagation, intuitively | Deep Learning Chapter 3</a>
</center>""")

md(r"""### Chapter 4 — Backpropagation calculus

The chain rule made concrete — the math behind `loss.backward()`. Optional for the hands-on lab, essential if you want to truly understand what PyTorch computes for you.

<center>
<iframe width="800" height="450" src="https://www.youtube.com/embed/tIeHLnjs5U8" title="Backpropagation calculus" frameborder="0" allowfullscreen></iframe>
<br>
<a href="https://www.youtube.com/watch?v=tIeHLnjs5U8&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi&index=4" target="_blank">Backpropagation calculus | Deep Learning Chapter 4</a>
</center>

> **A question that often comes up here:** *"Do I need the calculus in Chapter 4 to do the lab?"* No. PyTorch's autograd computes every derivative for you — that is the whole point of a framework. Chapters 1 and 2 are enough to follow Section 4 with understanding; Chapters 3 and 4 are there for when you want to know *exactly* what `loss.backward()` is doing under the hood, which Section 6 also formalizes.""")

# ============================================================= 4. PYTORCH HANDS-ON
md(r"""# 4. PyTorch — Hands-On with FashionMNIST (End-to-End)

Now you train a network yourself. This section follows the official **PyTorch Quickstart** end to end on the **FashionMNIST** dataset — 70,000 small grayscale photos of clothing in 10 classes. The full arc is:

> **load data → build the model → train → test → save → load → predict.**

By the last cell you will have a trained model that looks at a photo it has never seen and tells you whether it is a sneaker, a coat, or a bag — and is usually right.

> 💡 **Pro tip:** Use a GPU runtime to speed up training — *Runtime > Change runtime type > GPU*. Everything here also runs on CPU; five epochs take a couple of minutes.

Colab already ships with `torch` and `torchvision`. Locally, uncomment the install line below.""")

code(r"""# Colab already has PyTorch installed. Locally, uncomment:
# !pip install torch torchvision -q

import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
import matplotlib.pyplot as plt

print("PyTorch version:", torch.__version__)""")

# ---- 4.1 working with data ----
md(r"""## 4.1 Working with data

PyTorch has two data primitives: `Dataset` stores the samples and their labels, and `DataLoader` wraps an iterable around the `Dataset` so we can serve **mini-batches**, shuffle each epoch, and (optionally) load in parallel. `torchvision` ships **FashionMNIST** as a ready-made `Dataset`: 60,000 training images and 10,000 test images, each a 28×28 grayscale image with a label from one of 10 classes.

`ToTensor()` is the transform that converts each image to a tensor with pixel values scaled to `[0, 1]`.""")
code(r"""# Download the FashionMNIST training and test data (first run downloads ~30 MB).
training_data = datasets.FashionMNIST(
    root="data", train=True,  download=True, transform=ToTensor()
)
test_data = datasets.FashionMNIST(
    root="data", train=False, download=True, transform=ToTensor()
)

# Human-readable class names (the official Quickstart calls this list `classes`).
labels_map = {0:"T-Shirt", 1:"Trouser", 2:"Pullover", 3:"Dress", 4:"Coat",
              5:"Sandal", 6:"Shirt", 7:"Sneaker", 8:"Bag", 9:"Ankle Boot"}

print("Training images:", len(training_data), "| Test images:", len(test_data))""")

md(r"""We wrap the datasets in `DataLoader`s. We use a **batch size of 64** — the network will see 64 images, update its weights, then see the next 64. Shuffling the training data each epoch reduces overfitting.""")
code(r"""batch_size = 64
train_dataloader = DataLoader(training_data, batch_size=batch_size, shuffle=True)
test_dataloader  = DataLoader(test_data,     batch_size=batch_size)

# Inspect one batch: N images, C channels, H x W pixels.
for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break""")

md(r"""Let's actually *look* at the data — a 3×3 grid of random training images with their labels. This is the kind of "EDA snapshot" you did in nb01, now on image data.""")
code(r"""figure = plt.figure(figsize=(8, 8))
cols, rows = 3, 3
for i in range(1, cols * rows + 1):
    sample_idx = torch.randint(len(training_data), size=(1,)).item()
    img, label = training_data[sample_idx]
    figure.add_subplot(rows, cols, i)
    plt.title(labels_map[label])
    plt.axis("off")
    plt.imshow(img.squeeze(), cmap="gray")
plt.show()""")

md(r"""📖 **Reference — the official *Datasets & DataLoaders* page** (embedded for convenience):""")
code(iframe("https://pytorch.org/tutorials/beginner/basics/data_tutorial.html"))

# ---- 4.2 build the model ----
md(r"""## 4.2 Build the model

First, get the device. We train on an accelerator (CUDA GPU, Apple MPS, ...) if one is available; otherwise the CPU. The model and the data have to live on the same device.""")
code(r"""device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")""")

md(r"""We define the network by subclassing `nn.Module`: the layers go in `__init__`, and `forward` says how data flows through them. This is a **multi-layer perceptron** — flatten the 28×28 image into 784 numbers, then three fully-connected (`Linear`) layers with **ReLU** activations between them, ending in **10 logits** (one score per class).

- `nn.Flatten()` turns the 2D image (28×28) into a 1D vector of 784 values.
- `nn.Linear(28*28, 512)` projects those 784 values into 512 learned features (`output = x · W + b`).
- `nn.ReLU()` keeps positives, zeroes negatives — the non-linearity that lets the network learn complex patterns.
- The final `nn.Linear(512, 10)` outputs the 10 class logits.""")
code(r"""class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)""")

md(r"""### Inside the model, layer by layer

To see what each layer does to the data, push a sample mini-batch of **3 images** through the pieces one at a time and watch the shapes change.""")
code(r"""input_image = torch.rand(3, 28, 28)
print("input batch:", input_image.size())

flatten = nn.Flatten()
flat_image = flatten(input_image)
print("after Flatten:", flat_image.size())          # 3 x 784

layer1 = nn.Linear(in_features=28*28, out_features=20)
hidden1 = layer1(flat_image)
print("after Linear(784->20):", hidden1.size())     # 3 x 20

print("\nBefore ReLU (first row):\n", hidden1[0])
hidden1 = nn.ReLU()(hidden1)
print("\nAfter ReLU (negatives -> 0):\n", hidden1[0])""")

md(r"""The last `Linear` layer returns **logits** (raw scores in `[-∞, ∞]`). Passing them through `nn.Softmax` turns them into **probabilities** that sum to 1, and `argmax` picks the predicted class. Right now the model is **untrained**, so this prediction is essentially a random guess — training (next) is what makes it meaningful.""")
code(r"""# One forward pass on a real test image — UNTRAINED model, so expect a wrong guess.
X0, y0 = test_data[0]
model.eval()
with torch.no_grad():
    logits = model(X0.unsqueeze(0).to(device))
    pred_probab = nn.Softmax(dim=1)(logits)
    guess = pred_probab.argmax(1).item()
print(f"Untrained guess: {labels_map[guess]}  |  Actual: {labels_map[y0]}")""")

md(r"""📖 **Reference — the official *Build the Neural Network* and *Autograd* pages:**""")
code(iframe("https://pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html"))
code(iframe("https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html"))

# ---- 4.3 train ----
md(r"""## 4.3 Optimize the model parameters (train it)

To train, we need three things:

1. A **loss function** that measures how wrong the predictions are. For multi-class classification we use `nn.CrossEntropyLoss` (it combines softmax + negative-log-likelihood, so we feed it the raw logits).
2. An **optimizer** that adjusts the weights to reduce the loss. We use **stochastic gradient descent (SGD)** with a learning rate of `1e-3` — the downhill step from Chapter 2.
3. The **hyperparameters**: how many times to sweep the data (**epochs**), the **batch size** (already 64), and the **learning rate**.

Inside the training loop, optimization happens in three steps you saw in the videos: `loss.backward()` computes the gradients (backpropagation), `optimizer.step()` nudges the weights downhill, and `optimizer.zero_grad()` resets the gradients for the next batch.""")
code(r"""learning_rate = 1e-3
epochs = 5

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)""")

md(r"""We define a **train loop** (sweep the training data, update the weights) and a **test loop** (sweep the held-out test data, report accuracy and loss without updating anything). The test loop is our honest check that the model is actually getting better on images it did not train on.""")
code(r"""def train_loop(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()  # training mode (matters for dropout/batchnorm; harmless here)
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction and loss
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation (the three-step update)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * batch_size + len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")


def test_loop(dataloader, model, loss_fn):
    model.eval()  # evaluation mode
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, correct = 0, 0

    with torch.no_grad():  # no gradients needed for evaluation
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")""")

md(r"""Now run the optimization loop. Each epoch is one full pass over the 60,000 training images. Watch the loss fall and the test accuracy climb — that is your network learning. (Feel free to increase `epochs` to push accuracy higher.)""")
code(r"""for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train_loop(train_dataloader, model, loss_fn, optimizer)
    test_loop(test_dataloader, model, loss_fn)
print("Done!")""")

md(r"""📖 **Reference — the official *Optimizing Model Parameters* page:**""")
code(iframe("https://pytorch.org/tutorials/beginner/basics/optimization_tutorial.html"))

md(r"""> **A question that often comes up here:** *"My accuracy is only \~65% — is that broken?"* No — that is exactly what 5 epochs of plain SGD gives on this network, and it is the official Quickstart's result. It is already far better than the 10% you would get by guessing. To do better, the usual levers are: train for more epochs, switch the optimizer to `torch.optim.Adam`, or use a convolutional network (Section 7) instead of a flat MLP — CNNs are built for images and routinely top 90% here.""")

# ---- 4.4 save ----
md(r"""## 4.4 Save the model

PyTorch stores a model's learned parameters in an internal **state dictionary** (`state_dict`). We persist it with `torch.save`. This is the artifact you would hand to a deployment pipeline — the same idea as the `joblib` model persistence you did in nb18, but for a neural network.""")
code(r"""torch.save(model.state_dict(), "model.pth")
print("Saved PyTorch Model State to model.pth")""")

# ---- 4.5 load ----
md(r"""## 4.5 Load the model

To reload, recreate the model structure (the class defines it), then load the saved weights. `weights_only=True` is the recommended, safer way to load a `state_dict`. Always call `model.eval()` before inference so any dropout/batch-norm layers behave deterministically.""")
code(r"""model = NeuralNetwork().to(device)
model.load_state_dict(torch.load("model.pth", weights_only=True))
model.eval()
print("Reloaded the trained model from disk.")""")

md(r"""📖 **Reference — the official *Save & Load the Model* page:**""")
code(iframe("https://pytorch.org/tutorials/beginner/basics/saveloadrun_tutorial.html"))

# ---- 4.6 predict ----
md(r"""## 4.6 Make predictions — the end-to-end payoff

The model is trained, saved, and reloaded. Now use it the way you finally care about: hand it an image and read its prediction. We take the first test image, run it through the model, and compare the predicted label to the truth.""")
code(r"""model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
    x = x.to(device)
    pred = model(x)
    predicted, actual = labels_map[pred[0].argmax(0).item()], labels_map[y]
print(f'Predicted: "{predicted}", Actual: "{actual}"')""")

md(r"""### 🎲 Predict a grid of random photos

Here is the full experience: draw nine **random** test photos, predict each one with the trained model, and show the image with its predicted vs. true label — **green** when the model is right, **red** when it is wrong. Re-run the cell for a fresh nine. With a trained model, most titles are green.""")
code(r"""model.eval()
figure = plt.figure(figsize=(9, 9))
cols, rows = 3, 3
for i in range(1, cols * rows + 1):
    idx = torch.randint(len(test_data), size=(1,)).item()
    img, true_label = test_data[idx]
    with torch.no_grad():
        pred_label = model(img.unsqueeze(0).to(device)).argmax(1).item()
    is_correct = (pred_label == true_label)
    figure.add_subplot(rows, cols, i)
    plt.title(f"Pred: {labels_map[pred_label]}\nTrue: {labels_map[true_label]}",
              color=("green" if is_correct else "red"), fontsize=10)
    plt.axis("off")
    plt.imshow(img.squeeze(), cmap="gray")
plt.tight_layout()
plt.show()""")

md(r"""> **A question that often comes up here:** *"The untrained model in 4.2 guessed wrong, and now most guesses are right — what actually changed?"* Only the **weights**. The architecture is identical; training adjusted the millions of numbers inside the `Linear` layers (via the gradient-descent loop you ran in 4.3) so that the same `forward` pass now maps clothing images to the correct class most of the time. That is the entire story of supervised deep learning: fixed architecture, learned weights, and a loss function pulling those weights toward "right." You just did it end to end.

That completes the hands-on lab. The rest of the notebook builds the formal understanding underneath what you just ran — the single-layer math, how fitting really works, and the CNN/RNN inventions — and closes with when deep learning is (and is not) the right tool.""")

# ============================================================= 5. SINGLE LAYER NN
md(r"""# 5. Single Layer Neural Network (the math)

You just trained a multi-layer network. Here is the math of the simplest version — a single hidden layer — which is the building block for everything else. A single-layer network with $K$ hidden units computes:

$$
\begin{align*}
f(X) &= \beta_0 + \sum_{k=1}^{K} \beta_k h_k(X) \\
     &= \beta_0 + \sum_{k=1}^{K} \beta_k\, g\!\left(w_{k0} + \sum_{j=1}^{p} w_{kj} X_j \right).
\end{align*}
$$""")

md(img("10_1-1.png", 560, "Single layer neural network diagram",
       "Network diagram of a single-layer neural network."))

md(r"""**Reading the diagram.** Neural networks are often drawn as **network diagrams**:

- **Input layer (orange circles):** $X_1, X_2, X_3, X_4$ — observed features from the dataset.
- **Hidden layer (blue circles):** $A_1, \ldots, A_5$ — transformations (activations) computed from the inputs.
- **Output layer (pink circle):** $f(X) \to Y$ — also observed (a label or continuous response).

**Observed vs. latent.** The $X_j$ are observed (inputs) and $Y$ is observed (the response). The **hidden units** $A_k$ are **not** observed — they are learned transformations.

**The hidden layer as transformations.** Each activation is

$$
A_k = h_k(X) = g\!\Bigl(w_{k0} + \sum_{j=1}^{p} w_{kj} X_j\Bigr),
$$

where $g(\cdot)$ is a non-linear function (ReLU, sigmoid, tanh) and the $w_{kj}$ are weights learned during training. Each hidden unit has a *different* set of weights, hence a different transformation. The network learns all the weights $w_{kj}, w_{k0}, \beta_k, \beta_0$ during training — exactly the `optimizer.step()` updates you watched run in Section 4.""")

md(r"""## Single Layer Neural Network: Details""")
md(img("10_2-1.png", 620, "Activation function details"))
md(r"""- $A_k = h_k(X) = g\!\left(w_{k0} + \sum_{j=1}^{p} w_{kj} X_j\right)$ are the **activations** in the *hidden layer* — a non-linear transformation of a linear function.
- $g(z)$ is the **activation function**. Two popular choices: the **sigmoid** and the **rectified linear unit (ReLU)** — the `nn.ReLU()` from your lab.
- Activation functions in hidden layers are typically non-linear; otherwise the whole model collapses to a linear model.
- For regression, the model is fit by minimizing $\sum_{i=1}^{n} (y_i - f(x_i))^2$.""")

md(r"""## NN Example: MNIST Digits""")
md(img("10_3a-1.png", 360, "MNIST digit examples"))
md(img("10_3b-1.png", 420, "MNIST two-layer network"))
md(r"""- **Handwritten digits:** 28×28 grayscale images, 60K train / 10K test — the same shape as the FashionMNIST images you just classified. Features are the 784 pixel values $\in (0, 255)$; labels are the digit class $0\text{–}9$.
- A two-layer network with **256 units** at the first layer, **128 units** at the second, and **10 units** at the output has — along with the biases — **235,146 parameters**.

> **A question that often comes up here:** *"235,146 parameters for a tiny image — isn't that wildly overfit?"* It would be for a noisy tabular problem with a few thousand rows. But image recognition has a very **high signal-to-noise ratio** and a huge training set, so the network has enough data to pin those parameters down. This is the same theme you will see again under "double descent" — over-parameterization is far less dangerous when the signal is strong and the data is large.""")

# ============================================================= 6. FITTING NN
md(r"""# 6. Fitting Neural Networks

You watched the intuition for this in Section 3 (Chapters 2–4) and ran it in Section 4's train loop. Here is the formal version.

We fit the network by minimizing squared error:

$$
\min_{\{w_k\}_{1}^K,\, \beta}\; \frac{1}{2} \sum_{i=1}^n \bigl(y_i - f(x_i)\bigr)^2,
\qquad
f(x_i) = \beta_0 + \sum_{k=1}^K \beta_k\, g\!\left(w_{k0} + \sum_{j=1}^p w_{kj} x_{ij}\right).
$$

This problem is hard because the objective is **non-convex**. Despite that, effective algorithms optimize complex networks efficiently.

## Non-convex functions and gradient descent

Let $R(\theta) = \frac{1}{2}\sum_{i=1}^n (y_i - f_\theta(x_i))^2$ with $\theta = (\{w_k\}_{1}^K, \beta)$.""")
md(img("10_17-1.png", 560, "Gradient descent on a non-convex surface"))
md(r"""We compute the **gradient vector** $\nabla R(\theta^t)$ (the partial derivatives at the current guess), which points *uphill*, and step the other way:

$$
\theta^{t+1} \gets \theta^t - \rho\, \nabla R(\theta^t),
$$

where $\rho$ is the **learning rate** (your `lr=1e-3`). If we had started elsewhere, we might descend into a **local** rather than the global minimum — hard to tell apart in high dimensions.""")

md(r"""## Gradients and backpropagation

Because $R(\theta) = \sum_{i=1}^n R_i(\theta)$ is a sum, its gradient is the sum of gradients. With $z_{ik} = w_{k0} + \sum_{j=1}^p w_{kj} x_{ij}$, backpropagation applies the **chain rule**:

$$
\frac{\partial R_i(\theta)}{\partial \beta_k}
= -(y_i - f_\theta(x_i)) \cdot g(z_{ik}),
\qquad
\frac{\partial R_i(\theta)}{\partial w_{kj}}
= -(y_i - f_\theta(x_i)) \cdot \beta_k \cdot g'(z_{ik}) \cdot x_{ij}.
$$

This is exactly the calculation `loss.backward()` ran for you in Section 4.

## Tricks of the trade

- **Stochastic gradient descent (SGD).** Rather than use *all* the data each step, use a small **mini-batch** drawn at random — your `batch_size=64`.
- **Epoch.** One epoch is the number of mini-batch updates needed to process $n$ samples once — for FashionMNIST, $60{,}000/64 \approx 938$ updates per epoch.
- **Regularization.** Ridge and lasso shrink the weights; two other popular forms are **dropout** and **augmentation**, next.""")

md(r"""## Dropout learning""")
md(img("10_1_4-1.png", 560, "Dropout"))
md(r"""- At each SGD update, randomly **remove** units with probability $\phi$, and scale up the weights of those retained by $1/(1-\phi)$ to compensate.
- In simple cases this is equivalent to **ridge** regularization; the other units *stand in* for those temporarily removed.
- Similar in spirit to randomly omitting variables when growing trees in random forests.

## Ridge and data augmentation""")
md(img("10_1_5-1.png", 560, "Data augmentation as ridge"))
md(r"""- Make many copies of each $(x_i, y_i)$ and add a small amount of Gaussian noise to the $x_i$ — a little cloud around each observation — but leave the $y_i$ alone.
- This makes the fit robust to small perturbations in $x_i$, and is equivalent to ridge regularization in an OLS setting.

## Data augmentation on the fly""")
md(img("10_1_6-1.png", 560, "Image data augmentation"))
md(r"""- Especially effective with SGD for images: natural transformations are applied to each training image as it is sampled, creating a cloud of images around each original.
- The label is left unchanged — in each case still **tiger**. Improves CNN performance and is similar to ridge.""")

md(r"""## Double descent""")
md(r"""- With neural networks, it seems better to have **too many** hidden units than too few — and more hidden layers better than few.
- Running SGD until *zero* training error often gives good out-of-sample error; adding even more units sometimes gives **even better** out-of-sample error.
- What happened to overfitting and the usual bias-variance trade-off?""")
md(img("10_20-1.png", 560, "The double-descent error curve"))
md(r"""**The double-descent error curve.** When $d \le 20$ the model is OLS and we see the usual bias-variance trade-off. When $d > 20$ we revert to the minimum-norm solution; as $d$ increases above 20, $\sum_{j=1}^d \hat\beta_j^2$ **decreases**, giving less wiggly solutions.""")
md(img("10_21-1.png", 560, "Less wiggly solutions for larger d"))
md(r"""By analogy, deep and wide networks fit by SGD down to zero training error often generalize well — *especially* in high signal-to-noise problems like image recognition, where the zero-error solution is mostly signal.""")

# ============================================================= 7. CNN
md(r"""# 7. Convolutional Neural Network — CNN

Your FashionMNIST MLP worked, but it threw away the *spatial* structure of the image the moment it called `Flatten`. CNNs keep that structure, which is why they dominate image tasks.

Neural networks rebounded around 2010 with big successes in **image classification**, just as massive labeled image databases were being accumulated.

## The CIFAR-100 database""")
md(img("cifar100.png", 720, "CIFAR-100 sample images"))
md(r"""- The figure shows 75 images from the **CIFAR-100** database (60,000 images, 20 superclasses, five classes each).
- Each image is 32×32 pixels with three 8-bit color channels (red, green, blue), organized as a 3-D array called a **feature map**: two spatial axes and one **channel** axis.
- There is a designated training set of 50,000 images and a test set of 10,000.""")

md(r"""## The convolutional network hierarchy""")
md(img("10_1_2-1.png", 560, "CNN feature hierarchy"))
md(r"""- CNNs mimic how humans classify images — recognizing patterns anywhere in the image.
- The network first identifies **low-level features** (edges, color patches), then combines them into **higher-level features** (parts of ears or eyes), and finally into class probabilities.
- This hierarchy is built from two specialized hidden-layer types: **convolution layers** (search for small patterns) and **pooling layers** (downsample to keep a prominent subset).""")

md(r"""## Convolution layer

A convolution layer is made of many **convolution filters**, each a small template that detects a local feature. The operation multiplies matching matrix elements and sums them:

$$
\text{Input} =
\begin{bmatrix} a & b & c \\ d & e & f \\ g & h & i \\ j & k & l \end{bmatrix},
\quad
\text{Filter} =
\begin{bmatrix} \alpha & \beta \\ \gamma & \delta \end{bmatrix}
\;\Rightarrow\;
\text{Convolved} =
\begin{bmatrix}
a\alpha + b\beta + d\gamma + e\delta & b\alpha + c\beta + e\gamma + f\delta \\
d\alpha + e\beta + g\gamma + h\delta & e\alpha + f\beta + h\gamma + i\delta \\
g\alpha + h\beta + j\gamma + k\delta & h\alpha + i\beta + k\gamma + l\delta
\end{bmatrix}.
$$

If a 2×2 patch resembles the filter, it produces a large value — so the convolved image **highlights regions that resemble the filter**. The filters are **learned** during training.""")
md(r"""## Convolution example""")
md(img("10_7-1.png", 640, "Convolution with vertical/horizontal filters"))
md(r"""- Convolution finds common patterns that occur in different parts of the image.
- The two filters shown highlight vertical and horizontal stripes; with three color channels, each filter has one slice per channel, summed.
- The weights in the filters are **learned** by the network.""")

md(r"""## Pooling layer

A pooling layer condenses a large image into a smaller summary:

$$
\text{Max pool}
\begin{bmatrix}
1 & 2 & 5 & 3 \\ 3 & 0 & 1 & 2 \\ 2 & 1 & 3 & 4 \\ 1 & 1 & 2 & 0
\end{bmatrix}
\rightarrow
\begin{bmatrix} 3 & 5 \\ 2 & 4 \end{bmatrix}
$$

Each non-overlapping 2×2 block is replaced by its maximum — sharpening feature identification, allowing **locational invariance**, and reducing the dimension by a factor of 4.

## Architecture of a CNN""")
md(img("10_8-1.png", 640, "Full CNN architecture"))
md(r"""- Many convolve + pool layers, with small (e.g. 3×3) filters; each filter creates a new channel.
- As pooling reduces size, the number of channels is typically increased.
- The number of layers can be very large — **resnet50**, trained on **imagenet** (1000 classes), has 50 layers.""")

md(r"""## CNN example: pretrained networks to classify images""")
md(img("10_1_3-1.png", 460, "resnet50 classifying photographs"))
md(r"""Here a 50-layer **resnet50** trained on the 1000-class **imagenet** corpus classifies photographs. This is the everyday way analysts use CNNs: **download a pretrained network** and apply it, rather than train one from scratch — the natural next step after the from-scratch MLP you trained in Section 4.""")

# ============================================================= 8. DOC CLASSIFICATION
md(r"""# 8. Document Classification

The **IMDB** corpus consists of user movie reviews, each labeled for **sentiment** (positive or negative). Here is the start of a negative review:

> *This has to be one of the worst films of the 1990s. When my friends & I were watching this film ... we just sat & watched the first half an hour with our jaws touching the floor at how bad it really was...*

There are labeled training and test sets, each with 25,000 reviews, balanced on sentiment. **Goal:** predict the sentiment of a review.

## Featurization: bag-of-words

- From a dictionary, take the 10K most frequent words.
- Represent each document as a binary vector of length $p = 10\text{K}$, scoring a 1 in every position whose word occurs.
- With $n$ documents, we get an $n \times p$ **sparse** feature matrix $\mathbf{X}$.
- Bag-of-words are **unigrams**; we can instead use **bigrams** or, in general, **m-grams**.""")
md(img("10_11-1.png", 380, "Lasso vs neural network on IMDB"))
md(r"""**Lasso vs. neural network.** On these IMDB reviews, a simpler **lasso logistic regression** works as well as a two-hidden-layer neural network — an early hint of the "when to use deep learning" lesson at the end of this notebook.""")

# ============================================================= 9. RNN
md(r"""# 9. Recurrent Neural Networks — RNN

Often data arrive as **sequences**: documents (words in order), time series, recorded speech or music. RNNs take this sequential nature into account and build a **memory** of the past. The feature for each observation is a **sequence** of vectors $X = \{X_1, X_2, \ldots, X_L\}$; the target $Y$ is often a single variable (e.g. *Sentiment*) but can also be a sequence.

## Simple RNN architecture""")
md(img("10_12-1.png", 560, "Simple RNN architecture"))
md(r"""- The hidden layer is a sequence of vectors $A_\ell$, each receiving input $X_\ell$ and the previous hidden state $A_{\ell-1}$, and producing an output $O_\ell$.
- The **same** weights $\mathbf{W}, \mathbf{U}, \mathbf{B}$ are used at every step — hence **recurrent**.

## RNN in detail

With $X_\ell = (X_{\ell 1}, \ldots, X_{\ell p})$ and $A_\ell = (A_{\ell 1}, \ldots, A_{\ell K})$, the $k$-th hidden component is

$$
A_{\ell k} = g\!\left(w_{k0} + \sum_{j=1}^{p} w_{kj} X_{\ell j} + \sum_{s=1}^{K} u_{ks} A_{\ell-1,s}\right),
\qquad
O_\ell = \beta_0 + \sum_{k=1}^{K} \beta_k A_{\ell k}.
$$

**Three variants you will hear named:**

- **Vanilla RNN** — the original; trains poorly on long sequences (gradients vanish).
- **LSTM** (Long Short-Term Memory) — adds gates that learn what to remember and forget. The default for sequence problems from \~2014 to \~2018.
- **Transformer** — replaces recurrence with attention, processes the whole sequence in parallel, and now dominates language and increasingly time series. ChatGPT, Claude, and every modern LLM are transformers.""")

md(r"""# 10. RNN for Document Classification

- A document is a sequence of words $\{\mathcal{W}_\ell\}_{1}^{L}$, truncated/padded to a common length $L$ (here $L = 500$).
- Each word is a **one-hot** binary vector of length 10K — extremely sparse, and it would not work well directly.
- Instead we use a lower-dimensional pretrained **word embedding** matrix $\mathbf{E}$, reducing each length-10K binary vector to a real vector of dimension $m \ll 10\text{K}$.""")
md(img("10_13a-1.png", 500, "Word embedding (one-hot)"))
md(img("10_13b-1.png", 500, "Word embedding (dense)"))
md(r"""Embeddings are pretrained on very large corpora; **word2vec** and **GloVe** are popular. This embedding idea is the direct ancestor of the token embeddings inside today's LLMs.""")

# ============================================================= 11. RNN TIME SERIES
md(r"""# 11. RNN for Time Series Forecasting""")
md(img("10_14-1.png", 720, "New York Stock Exchange data"))
md(r"""**New York Stock Exchange data.** Three daily time series for December 3, 1962 to December 31, 1986 (6,051 trading days): **Log trading volume**, **Dow Jones return**, and **Log volatility**. **Goal:** predict **Log trading volume** tomorrow, given the past values of all three.

## Autocorrelation""")
md(img("10_15-1.png", 560, "Autocorrelation function"))
md(r"""- The **autocorrelation** at lag $\ell$ is the correlation of all pairs $(v_t, v_{t-\ell})$ that are $\ell$ trading days apart.
- Sizable correlations give us confidence that past values help predict the future — exactly the lag-feature idea from nb16.

## RNN forecaster

We extract many short mini-series of length $L$ (the **lag**):

$$
X_1 = \begin{pmatrix} v_{t-L} \\ r_{t-L} \\ z_{t-L} \end{pmatrix},
\;\cdots,\;
X_L = \begin{pmatrix} v_{t-1} \\ r_{t-1} \\ z_{t-1} \end{pmatrix},
\qquad Y = v_t.
$$

With $T = 6{,}051$ and $L = 5$, we get 6,046 $(X, Y)$ pairs and fit an RNN with 12 hidden units per lag step.""")
md(img("10_16-1.png", 560, "RNN forecasts vs truth"))
md(r"""**Results.** $R^2 = 0.42$ for the RNN, versus $R^2 = 0.18$ for the naive "use yesterday's value" approach.

## Autoregression comparison

A traditional **order-$L$ autoregression** $AR(L)$ fits $\hat{v}_t = \hat\beta_0 + \hat\beta_1 v_{t-1} + \cdots + \hat\beta_L v_{t-L}$ by OLS:

- $R^2 = 0.41$ for $AR(5)$ (16 parameters)
- $R^2 = 0.42$ for the RNN (205 parameters)
- $R^2 = 0.46$ for all models if we add **day_of_week**

> **A question that often comes up here:** *"The RNN has 205 parameters and the AR(5) has 16, and they tie — so why ever use the RNN here?"* You wouldn't, for this series. On noisy, low-volume series the simpler model wins on every practical axis (speed, interpretability, deployment). The RNN earns its parameters only when the dependence is strongly non-linear *and* you have enough data — the exact theme of the next section.""")

# ============================================================= 12. WHEN TO USE
md(r"""# 12. When to Use Deep Learning

- **CNNs** have had enormous success in image classification and are entering medical diagnosis (mammography, ophthalmology, MRI, X-rays).
- **RNNs** (and transformers) have had big wins in speech, language translation, and forecasting.

**Should we always use deep learning?** No.

- The big successes occur when the **signal-to-noise ratio** is high (image recognition, language translation), datasets are large, and overfitting is not the main worry.
- For **noisier** data, simpler models often work better: on the **NYSE** data the **AR(5)** tied the RNN; on the **IMDB** reviews a linear model did as well as the neural network.""")
md(img("2_7-1.png", 480, "Flexibility vs interpretability",
       "The flexibility-interpretability trade-off (ISLR Figure 2.7)."))
md(r"""**Occam's razor.** Prefer simpler models when they work as well — they are more interpretable. This is the same trade-off curve from the start of the course; deep learning sits at the far flexible-but-opaque end.""")

md(r"""## A four-question rubric

Before you reach for deep learning, run the problem through these four questions:

1. **Data shape.** Is the input an image, audio, long text sequence, or a high-dimensional structured object? If yes, lean DL. If it is a tabular row, lean classical ML.
2. **Sample size.** Do you have at least tens of thousands of labeled examples (ideally millions)? If yes, DL has the data it needs. With hundreds or low thousands, classical ML almost always wins.
3. **Compute budget.** Can you spend \~10× the training time and \~50× the inference cost of a tree ensemble? If yes, DL is in scope. If you need a CPU model that predicts in milliseconds, prefer classical ML.
4. **Interpretability requirement.** Does the stakeholder need a feature-by-feature explanation for every prediction? If yes, DL adds friction. If predictions only need to be accurate, DL is in scope.

**Verdict rule:** answer "yes" to **at least three** questions for DL to be the right *primary* tool. Otherwise, classical ML first.""")

md(r"""## 📝 PAUSE-AND-DO Exercise 1 — When Is Deep Learning the Right Tool? (10 minutes)

**Task:** Apply the four-question rubric to **two** problems: the Bank Churn case competition (nb18) and the DemandCo monthly forecast (nb16). For each, answer the four questions and produce one verdict — *deep learning is / is not the right primary tool*.""")

md(r"""### YOUR RUBRIC ANSWERS HERE:

**Problem A — Bank Churn case competition (tabular, \~10K rows, churn probability for the retention team):**

1. Data shape: *[tabular / sequential / image — and DL lean?]*
2. Sample size: *[count + lean]*
3. Compute budget: *[lean]*
4. Interpretability: *[lean]*
5. **Verdict:** *[DL primary / Classical ML primary]*  *[one sentence why]*

**Problem B — DemandCo monthly demand forecast (60 months, procurement target):**

1. Data shape: *[lean]*
2. Sample size: *[lean]*
3. Compute budget: *[lean]*
4. Interpretability: *[lean]*
5. **Verdict:** *[DL primary / Classical ML primary]*  *[one sentence why]*""")

md(r"""## One honest demo — `MLPClassifier` vs. Gradient Boosting on tabular data

Now the comparison the VP of Strategy actually wants: a feed-forward neural network on a Bank-Churn-style classification problem, evaluated on the **same CV folds**, against gradient boosting from nb13. We use scikit-learn's `MLPClassifier` (an off-the-shelf MLP) so it runs on a CPU in under a minute — no PyTorch needed. We report the mean ROC-AUC with the same Student's *t* 95% CI from nb08.""")
code(r"""import pandas as pd, numpy as np, matplotlib.pyplot as plt
from scipy import stats
from sklearn.datasets import make_classification
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier

RANDOM_SEED = 474
np.random.seed(RANDOM_SEED)

# Synthetic tabular classification — a realistically noisy business table:
# modest class separation and 10% label noise, the regime where trees and
# nets tie. (same shape as nb15: 5000 rows, 20 features)
X_tab, y_tab = make_classification(
    n_samples=5000, n_features=20, n_informative=6, n_redundant=4,
    n_classes=2, flip_y=0.10, class_sep=0.7, random_state=RANDOM_SEED,
)
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)

mlp_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", MLPClassifier(hidden_layer_sizes=(64, 32), activation="relu",
                          max_iter=200, random_state=RANDOM_SEED)),
])
gbm = GradientBoostingClassifier(
    n_estimators=300, max_depth=3, learning_rate=0.05, random_state=RANDOM_SEED,
)

mlp_aucs = cross_val_score(mlp_pipe, X_tab, y_tab, scoring="roc_auc", cv=cv, n_jobs=-1)
gbm_aucs = cross_val_score(gbm,      X_tab, y_tab, scoring="roc_auc", cv=cv, n_jobs=-1)

k = 5
t_crit = stats.t.ppf(0.975, df=k - 1)  # ~2.776 — same Student's t constant from nb08

def _row(scores):
    m = float(scores.mean()); sd = float(scores.std(ddof=1))
    half_w = t_crit * sd / np.sqrt(k)
    return {'AUC_mean': m, 'AUC_sd': sd, 'AUC_half_w': half_w,
            'AUC_ci_low': m - half_w, 'AUC_ci_high': m + half_w}

summary = pd.DataFrame({
    'MLPClassifier (64,32)': _row(mlp_aucs),
    'GradientBoosting':      _row(gbm_aucs),
}).T
print(summary.round(4))

mlp = summary.loc['MLPClassifier (64,32)']
gbm_row = summary.loc['GradientBoosting']
overlap = not (mlp['AUC_ci_high'] < gbm_row['AUC_ci_low'] or gbm_row['AUC_ci_high'] < mlp['AUC_ci_low'])
if not overlap:
    winner = 'MLPClassifier' if mlp['AUC_mean'] > gbm_row['AUC_mean'] else 'GradientBoosting'
    print(f'\nVerdict: CIs do NOT overlap -> {winner} wins outright (CI-clear margin).')
else:
    print('\nVerdict: CIs overlap -> statistical tie -> simpler / faster model wins by default.')""")

md(r"""**Reading the output:** On a 5,000-row tabular problem with 20 features, the MLP and the gradient-boosted ensemble usually land within a few thousandths of each other — well inside the CV 95% CI. That overlapping interval is the empirical answer to the VP's question: deep learning **does not** outperform a tuned tree ensemble on this kind of data, and the ensemble is faster, more interpretable, and easier to deploy. The story flips when the input is an image (like the FashionMNIST photos you trained on) or a long text passage — there a CNN's or transformer's structural priors start paying for themselves.

> **A question that often comes up here:** *"What if I give the MLP more layers?"* You can — try `hidden_layer_sizes=(128, 64, 32)`. On this data the AUC will not move outside the CI; what *will* move is training time and the chance of training instability. Bigger is not better when the data structure does not need bigger. The next exercise has you confirm this yourself.""")

md(r"""## 📝 PAUSE-AND-DO Exercise 2 — Compare and Decide (10 minutes)

**Task:** Add a third candidate to the comparison — a deeper MLP with `hidden_layer_sizes=(128, 64, 32)` — and rerun the CV on the **same folds**. Then write three sentences answering the VP of Strategy's question.

**Hints:**
- Reuse the `mlp_pipe` pattern; only the `hidden_layer_sizes` argument changes.
- Do **not** change the CV splits — identical folds are what makes the comparison honest.""")

code(r"""# YOUR SOLUTION CODE HERE

# Hints:
# deep_pipe = Pipeline([
#     ("scaler", StandardScaler()),
#     ("clf", MLPClassifier(hidden_layer_sizes=(128, 64, 32), activation="relu",
#                           max_iter=300, random_state=RANDOM_SEED)),
# ])
# deep_aucs = cross_val_score(deep_pipe, X_tab, y_tab, scoring="roc_auc", cv=cv, n_jobs=-1)
# Build a 3-row summary table and compare the CIs.""")

md(r"""### INSTRUCTOR SOLUTION — Exercise 2""")
code(r"""# INSTRUCTOR SOLUTION
deep_pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", MLPClassifier(hidden_layer_sizes=(128, 64, 32), activation="relu",
                          max_iter=300, random_state=RANDOM_SEED)),
])
deep_aucs = cross_val_score(deep_pipe, X_tab, y_tab, scoring="roc_auc", cv=cv, n_jobs=-1)

summary3 = pd.DataFrame({
    'MLPClassifier (64,32)':      _row(mlp_aucs),
    'MLPClassifier (128,64,32)':  _row(deep_aucs),
    'GradientBoosting':           _row(gbm_aucs),
}).T
print(summary3.round(4))

print("\nAll three 95% CIs overlap: the deeper MLP does not beat the simpler MLP or"
      "\nthe gradient-boosted ensemble on this tabular data. Bigger is not better when"
      "\nthe data structure does not demand it.")""")

md(r"""<!-- INSTRUCTOR SOLUTION -->
**Reading the output:** Adding a third hidden layer leaves the AUC inside the same confidence interval — the deeper MLP is a statistical tie with both the shallow MLP and gradient boosting. The honest three-sentence answer to the VP writes itself: (1) on this tabular data all three models tie within the CV 95% CI; (2) this generalizes to Bank Churn because that problem is also a few-thousand-row tabular table, exactly where classical ML wins; (3) deep learning would earn its keep at TechCorp on a genuinely different data asset — say, classifying product photos (the FashionMNIST-style task from Section 4) or parsing free-text support tickets — not on the churn table.""")

md(r"""### YOUR ANSWER TO THE VP HERE:

**Three sentences for the VP of Strategy:**

1. *[Empirical comparison — which model won on this data, and by how much in CV CI terms?]*
2. *[Why this generalizes to the Bank Churn problem — data-shape and sample-size argument from the rubric]*
3. *[Where deep learning **would** earn its keep at TechCorp — name one concrete use case from the company's likely data assets]*""")

# ============================================================= 13. LLM
md(r"""# 13. Special Topic: Large Language Models (LLM)

The LLMs you have used all course (Gemini, ChatGPT, Claude) are **transformers** — the successor to the RNN. Four short videos build the intuition, from what an LLM is to how attention and memory work.

<center>
<iframe width="760" height="430" src="https://www.youtube.com/embed/LPZh9BOjkQs" title="LLMs explained briefly" frameborder="0" allowfullscreen></iframe>
<br><a href="https://www.youtube.com/watch?v=LPZh9BOjkQs" target="_blank">Large Language Models explained briefly</a>
<br><br>
<iframe width="760" height="430" src="https://www.youtube.com/embed/wjZofJX0v4M" title="Transformers" frameborder="0" allowfullscreen></iframe>
<br><a href="https://www.youtube.com/watch?v=wjZofJX0v4M" target="_blank">Transformers, the tech behind LLMs</a>
<br><br>
<iframe width="760" height="430" src="https://www.youtube.com/embed/eMlx5fFNoYc" title="Attention" frameborder="0" allowfullscreen></iframe>
<br><a href="https://www.youtube.com/watch?v=eMlx5fFNoYc" target="_blank">Attention in transformers, step-by-step</a>
<br><br>
<iframe width="760" height="430" src="https://www.youtube.com/embed/9-Jl0dxWQs8" title="LLM memory" frameborder="0" allowfullscreen></iframe>
<br><a href="https://www.youtube.com/watch?v=9-Jl0dxWQs8" target="_blank">How might LLMs store facts</a>
</center>""")

# ============================================================= ADDITIONAL + WRAP
md(r"""## Additional Material

- [3Blue1Brown: Neural Networks (the full series)](https://www.youtube.com/watch?v=aircAruvnKk&list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi)
- [PyTorch "Learn the Basics" tutorials](https://pytorch.org/tutorials/beginner/basics/intro.html) and the [Quickstart](https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html)
- [*Deep Learning*, by Goodfellow, Bengio, and Courville](https://www.deeplearningbook.org/)
- [Welch Labs: Neural Networks Demystified](https://www.youtube.com/watch?v=bxe2T-V8XRs&list=PLiaHhY2iBX9hdHaRr6b7XevZtgZRa1PoU)
- [Deep Learning with PyTorch: Step-by-Step](https://github.com/dvgodoy/PyTorchStepByStep/tree/master)""")

md(r"""## 14. Wrap-Up — Key Takeaways

1. **Deep learning is the *engineering stack* around old neural-network math.** Compute + data + frameworks were the bottleneck; the math was mostly already there in the 1980s.
2. **You trained a neural network end to end.** In Section 4 you loaded FashionMNIST, defined an `nn.Module`, ran a train/test loop across epochs, saved and reloaded the weights, and predicted real photos — the complete supervised-learning loop, in PyTorch.
3. **The three structural inventions are MLP, CNN, and RNN/Transformer.** MLP for tabular extras, CNN for images, RNN/Transformer for sequences. Name the right one for a problem and you have \~80% of what an analyst needs in this conversation.
4. **For tabular business problems with thousands of rows, gradient boosting almost always wins.** The MLP is a credible candidate but rarely the champion; the four-question rubric keeps you honest.
5. **PyTorch is the safer default to learn next** — the Hugging Face hub, almost every research paper, and the modern LLM ecosystem are PyTorch-first.

> **A question that often comes up here:** *"What about ChatGPT, Claude, and the LLMs we use every day?"* They are transformers (a successor to RNNs) trained on enormous text corpora. As an analyst you will mostly **use** them through APIs (you have done this all course via Gemini prompts) rather than train them. But the loop is the same one you ran in Section 4 — data, a loss, gradient descent — just at a vastly larger scale.

**Next stop — nb20: Course End and Reflection.** Tomorrow is delivery day: M4 poster, Kaggle final submission, intra-group peer evaluation, and the reflection survey that closes the course. Today you got both the language *and* the hands-on experience to answer, with evidence, when a colleague asks "should we be doing deep learning?".""")

md(r"""## Participation Assignment Submission Instructions

1. **Complete both PAUSE-AND-DO exercises.**
2. **Run all cells** (Section 4 downloads FashionMNIST and trains for a few epochs — give it a couple of minutes, or switch to a GPU runtime).
3. **Save with output** and submit `nb19_deep_learning_<your_lastname>.ipynb` to Brightspace.

### Next Step

- **Notebook 20** — Final submission + peer review (Day 20)

**Bibliography**
- ISLP, Chapter 10: Deep Learning (the textbook chapter behind this notebook's lecture slides).
- PyTorch "Learn the Basics" & Quickstart: <https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html>.
- *Deep Learning* by Goodfellow, Bengio, and Courville (free online): <https://www.deeplearningbook.org/>.
- 3Blue1Brown's *Deep Learning* video series (the best visual intuition online).""")

md(r"""<center>

# Thank you!

</center>""")

# ============================================================= WRITE
nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "name": "python3"},
        "language_info": {"name": "python"},
        "colab": {"provenance": []},
    },
    "nbformat": 4,
    "nbformat_minor": 0,
}

for c in nb["cells"]:
    c["source"] = c["source"].splitlines(keepends=True)

out = Path("notebooks/nb19_deep_learning_instructor.ipynb")
out.write_text(json.dumps(nb, indent=1, ensure_ascii=False))
print("Wrote", out, "with", len(cells), "cells")
