<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="author" content="Professor: Davi Moreira">
  <title>MGMT 47400: Predictive Analytics (Summer 2026 - 4-Week Intensive) –  MGMT 47400: Predictive Analytics </title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-96a67a1340eb436771fd03060be7db16.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title"><span style="font-size: 100%;"> MGMT 47400: Predictive Analytics </span></h1>
  <p class="subtitle"><span style="font-size: 150%;"> Linear Regression </span></p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Professor: Davi Moreira 
</div>
</div>
</div>

</section>
<section id="overview" class="slide level2 center">
<h2>Overview</h2>
<div class="columns">
<div class="column" style="text-align: center; justify-content: center; align-items: center;">
<ul>
<li><p>Recap</p></li>
<li><p>Linear Regression</p></li>
<li><p>Simple Linear Regression</p></li>
<li><p>Multiple Linear Regression</p></li>
<li><p>Considerations in the Regression Model</p>
<ul>
<li>Qualitative Predictors</li>
</ul></li>
</ul>
</div><div class="column" style="text-align: center; justify-content: center; align-items: center;">
<ul>
<li><p>Extensions of the Linear Model</p>
<ul>
<li>Interactions</li>
<li>Hierarchy</li>
</ul></li>
<li><p>Non-linear effects of predictors</p></li>
</ul>
</div></div>
<p><br></p>

<aside><div>
<p><em>This lecture content is inspired by and replicates the material from <a href="https://www.statlearning.com/">An Introduction to Statistical Learning</a>.</em></p>
</div></aside></section>
<section id="recap" class="slide level2 center">
<h2>Recap</h2>
<p><br></p>
<div class="columns">
<div class="column" style="width:50%;">
<details>
<summary>
<strong>What is Statistical Learning?</strong>
</summary>
<p style="font-size:80%;">
A framework to learn the relationship between predictors <span class="math inline">\(X\)</span> and an outcome <span class="math inline">\(Y\)</span> for prediction and inference, using parametric (e.g., linear/logistic regression) and non-parametric methods (e.g., trees, kNN).
</p>
</details>
<details>
<summary>
<strong>What is the difference between supervised and unsupervised learning?</strong>
</summary>
<p style="font-size:80%;">
<strong>Supervised:</strong> learn <span class="math inline">\(f: X \to Y\)</span> from labeled data to predict/explain <span class="math inline">\(Y\)</span>.<br> <strong>Unsupervised:</strong> find structure in <span class="math inline">\(X\)</span> without labels (e.g., clustering, dimensionality reduction).
</p>
</details>
<details>
<summary>
<strong>What is the curse of dimensionality?</strong>
</summary>
<p style="font-size:80%;">
With many features/predictors, data become sparse; distances degrade, required sample size grows rapidly, and generalization deteriorates, especially for local/partitioning methods.
</p>
</details>
</div><div class="column" style="width:50%;">
<details>
<summary>
<strong>What is the difference between overfitting and underfitting?</strong>
</summary>
<p style="font-size:80%;">
<strong>Overfitting:</strong> too flexible; captures noise (high variance); low training error, poor test error.<br> <strong>Underfitting:</strong> too simple; misses signal (high bias); high error on both train and test.
</p>
</details>
<details>
<summary>
<strong>Why assess accuracy on test data rather than training data?</strong>
</summary>
<p style="font-size:80%;">
Training accuracy is optimistically biased (evaluated on seen data). Test accuracy estimates out-of-sample performance and reveals overfitting.
</p>
</details>
</div></div>
</section>
<section id="participation" class="slide level2 center">
<h2>Participation</h2>
<ul>
<li><p>In pairs, ask AI:</p>
<ul>
<li>In the context of Statistical Learning, what is the fundamental difference between a <strong>regression</strong> problem and a <strong>classification</strong> problem in supervised learning, based on the nature of the outcome variable?</li>
</ul></li>
</ul>
<!--- In Statistical Learning, a **regression** problem predicts a **quantitative (continuous)** outcome, while a **classification** problem predicts a **qualitative (categorical)** outcome. --->
<div class="fragment">
<ul>
<li><p>Present the response you got to your right/left classmate. Do your understanding converge?</p></li>
<li><p>Submit your participation response.</p></li>
</ul>
</div>
</section>
<section>
<section id="linear-regression" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Linear Regression</h1>

</section>
<section id="linear-regression-1" class="slide level2 center">
<h2>Linear Regression</h2>
<div style="font-size: 80%;">
<ul>
<li><p>Linear regression is a simple approach to supervised learning. It assumes that the dependence of <span class="math inline">\(Y\)</span> on <span class="math inline">\(X_1, X_2, \ldots, X_p\)</span> is linear.</p></li>
<li><p>True regression functions are never linear!</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/3_1_1-1.png" class="quarto-figure quarto-figure-center" style="width:65.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Although it may seem overly simplistic, linear regression is extremely useful both conceptually and practically.</li>
</ul>
</div>
</section>
<section id="linear-regression-for-the-advertising-data" class="slide level2 center">
<h2>Linear Regression for the Advertising Data</h2>
<div style="font-size: 80%;">
<p>Consider the advertising data shown:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/2_1-1.png" class="quarto-figure quarto-figure-center" style="width:55.0%"></p>
</figure>
</div>
</div>
</div>
<p>Suppose that, in our job as business analysts, we are asked to suggest, based on this data, a <strong>marketing plan</strong> for next year that will result in high product sales. What information would be useful in order to provide such a recommendation?</p>
</div>
</section>
<section id="the-marketing-plan-guiding-questions" class="slide level2 center">
<h2>The Marketing Plan: Guiding Questions</h2>
<div style="font-size: 80%;">
<div class="columns">
<div class="column" style="font-size: 95%;">
<ol type="1">
<li class="fragment"><p><strong>Is there a relationship between advertising budget and sales?</strong><br>
Our first goal is to determine whether the data provide evidence of an association between advertising expenditure and sales. If the evidence is weak, one might argue that no money should be spent on advertising.</p></li>
<li class="fragment"><p><strong>How strong is the relationship between advertising budget and sales?</strong><br>
Assuming a relationship exists, how strong is it? Does knowledge of the advertising budget provide a lot of information about product sales?</p></li>
<li class="fragment"><p><strong>Which media are associated with sales?</strong><br>
Are all three media—TV, radio, and newspaper—associated with sales, or just one or two? We must separate the individual contribution of each medium to sales when money is spent on all three.</p></li>
<li class="fragment"><p><strong>How large is the association between each medium and sales?</strong><br>
For every dollar spent on a particular medium, by what amount will sales increase? How accurately can we predict this amount?</p></li>
</ol>
</div><div class="column" style="font-size: 95%;">
<ol start="5" type="1">
<li class="fragment"><p><strong>How accurately can we predict future sales?</strong><br>
For any given level of television, radio, or newspaper advertising, what is our prediction for sales, and what is the accuracy of this prediction?</p></li>
<li class="fragment"><p><strong>Is the relationship linear?</strong><br>
If the relationship between advertising expenditure and sales is approximately linear, then linear regression is appropriate. If not, we may need to transform the predictor(s) or the response so that linear regression can be used.</p></li>
<li class="fragment"><p><strong>Is there synergy among the advertising media?</strong><br>
Perhaps spending $50,000 on television advertising <strong>and</strong> $50,000 on radio advertising is associated with higher sales than allocating $100,000 to either television or radio individually. In marketing, this is known as a <strong>synergy</strong> effect; in statistics, it is called an <strong>interaction</strong> effect.</p></li>
</ol>
</div></div>
</div>
</section></section>
<section>
<section id="simple-linear-regression" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Simple Linear Regression</h1>

</section>
<section id="simple-linear-regression-using-a-single-predictor-x" class="slide level2 center">
<h2>Simple Linear Regression using a single predictor <span class="math inline">\(X\)</span></h2>
<div style="font-size: 80%;">
<ul>
<li>We assume a model:</li>
</ul>
<p><span class="math display">\[
  Y = \beta_0 + \beta_1X + \epsilon,
\]</span></p>
<p>where <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are two unknown constants that represent the <strong>intercept</strong> and <strong>slope</strong>, also known as <strong>coefficients</strong> or <strong>parameters</strong>, and <span class="math inline">\(\epsilon\)</span> is the error term.</p>
<div class="fragment">
<ul>
<li>Given some estimates <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> for the model coefficients, we predict future sales using:</li>
</ul>
<p><span class="math display">\[
  \hat{y} = \hat{\beta}_0 + \hat{\beta}_1x,
\]</span></p>
<p>where <span class="math inline">\(\hat{y}\)</span> indicates a prediction of <span class="math inline">\(Y\)</span> on the basis of <span class="math inline">\(X = x\)</span>. The hat symbol denotes an estimated value.</p>
</div>
</div>
</section>
<section id="estimation-of-the-parameters-by-least-squares" class="slide level2 center">
<h2>Estimation of the parameters by least squares</h2>
<div style="font-size: 80%;">
<ul>
<li><p>Let <span class="math inline">\(\hat{y}_i = \hat{\beta}_0 + \hat{\beta}_1 x_i\)</span> be the prediction for <span class="math inline">\(Y\)</span> based on the <span class="math inline">\(i\)</span>th value of <span class="math inline">\(X\)</span>. Then <span class="math inline">\(e_i = y_i - \hat{y}_i\)</span> represents the <span class="math inline">\(i\)</span>th <strong>residual</strong>.</p></li>
<li><p>We define the <strong>residual sum of squares</strong> (RSS) as:</p></li>
</ul>
<p><span class="math display">\[
    RSS = e_1^2 + e_2^2 + \cdots + e_n^2,
\]</span></p>
<p>or equivalently as:</p>
<p><span class="math display">\[
    RSS = (y_1 - \hat{\beta}_0 - \hat{\beta}_1 x_1)^2 + (y_2 - \hat{\beta}_0 - \hat{\beta}_1 x_2)^2 + \cdots + (y_n - \hat{\beta}_0 - \hat{\beta}_1 x_n)^2.
\]</span></p>
<div class="fragment">
<ul>
<li>The least squares approach selects the estimators <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> to minimize the RSS. The minimizing values can be shown to be:</li>
</ul>
<p><span class="math display">\[
    \hat{\beta}_1 = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^n (x_i - \bar{x})^2}, \quad
    \hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x},
\]</span></p>
<p>where <span class="math inline">\(\bar{y} \equiv \frac{1}{n} \sum_{i=1}^n y_i\)</span> and <span class="math inline">\(\bar{x} \equiv \frac{1}{n} \sum_{i=1}^n x_i\)</span> are the sample means.</p>
</div>
</div>
</section>
<section id="example-advertising-data" class="slide level2 center">
<h2>Example: Advertising Data</h2>
<div style="font-size: 80%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="figs/3_1-1.png" class="quarto-figure quarto-figure-center" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>The least squares fit for the regression of sales onto TV is shown. In this case a linear fit captures the essence of the relationship, although it is somewhat deficient in the left of the plot</p>
</div>
</section>
<section id="assessing-the-accuracy-of-the-coefficient-estimates" class="slide level2 center">
<h2>Assessing the Accuracy of the Coefficient Estimates</h2>
<div style="font-size: 70%;">
<ul>
<li>The standard error of an estimator reflects how it varies under repeated sampling:</li>
</ul>
<p><span class="math display">\[
  SE(\hat{\beta}_1)^2 = \frac{\sigma^2}{\sum_{i=1}^n (x_i - \bar{x})^2}, \quad SE(\hat{\beta}_0)^2 = \sigma^2 \left[ \frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^n (x_i - \bar{x})^2} \right].
\]</span></p>
<p>where <span class="math inline">\(\sigma^2 = Var(\epsilon)\)</span></p>
<div class="fragment">
<ul>
<li>These standard errors can be used to compute confidence intervals. A 95% confidence interval is defined as a range of values such that with 95% probability, the range will contain the true unknown value of the parameter. It has the form:</li>
</ul>
<p><span class="math display">\[
  \hat{\beta}_1 \pm 2 \cdot SE(\hat{\beta}_1).
\]</span></p>
</div>
<div class="fragment">
<ul>
<li>There is approximately a <strong>95% chance</strong> that the interval:</li>
</ul>
<p><span class="math display">\[
  \left[ \hat{\beta}_1 - 2 \cdot SE(\hat{\beta}_1), \hat{\beta}_1 + 2 \cdot SE(\hat{\beta}_1) \right]
\]</span></p>
<p>will contain the true value of <span class="math inline">\(\beta_1\)</span> (under a scenario where we obtained repeated samples like the present sample).</p>
<ul>
<li>For the advertising data, the <strong>95% confidence interval</strong> for <span class="math inline">\(\beta_1\)</span> is:</li>
</ul>
<p><span class="math display">\[
  [0.042, 0.053].
\]</span></p>
</div>
</div>
</section>
<section id="hypothesis-testing" class="slide level2 center">
<h2>Hypothesis Testing</h2>
<div style="font-size: 70%;">
<ul>
<li><strong>Standard errors</strong> can be used to perform <strong>hypothesis tests</strong> on coefficients. The most common hypothesis test involves testing the <strong>null hypothesis</strong>:</li>
</ul>
<p><span class="math display">\[
  H_0: \text{There is no relationship between } X \text{ and } Y
\]</span> versus the <strong>alternative hypothesis</strong>:</p>
<p><span class="math display">\[
  H_A: \text{There is some relationship between } X \text{ and } Y.
\]</span></p>
<div class="fragment">
<ul>
<li>Mathematically, this corresponds to testing:</li>
</ul>
<p><span class="math display">\[
  H_0: \beta_1 = 0
\]</span> versus:</p>
<p><span class="math display">\[
  H_A: \beta_1 \neq 0,
\]</span></p>
<p>since if <span class="math inline">\(\beta_1 = 0\)</span>, then the model reduces to <span class="math inline">\(Y = \beta_0 + \epsilon\)</span>, and <span class="math inline">\(X\)</span> is not associated with <span class="math inline">\(Y\)</span>.</p>
</div>
</div>
</section>
<section id="hypothesis-testing-1" class="slide level2 center">
<h2>Hypothesis Testing</h2>
<div style="font-size: 90%;">
<ul>
<li>To test the null hypothesis (<span class="math inline">\(H_0\)</span>), compute a <span class="math inline">\(t\)</span>-statistic as follows:</li>
</ul>
<p><span class="math display">\[
  t = \frac{\hat{\beta}_1 - 0}{SE(\hat{\beta}_1)}.
\]</span></p>
<ul>
<li><p>The <span class="math inline">\(t\)</span>-statistic follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n - 2\)</span> degrees of freedom under the null hypothesis (<span class="math inline">\(\beta_1 = 0\)</span>).</p></li>
<li><p>Using statistical software, we can compute the <span class="math inline">\(p\)</span>-value to determine the likelihood of observing a <span class="math inline">\(t\)</span>-statistic as extreme as the one calculated.</p></li>
</ul>
</div>
</section>
<section id="results-for-the-advertising-data" class="slide level2 center">
<h2>Results for the Advertising Data</h2>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-statistic</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Intercept</strong></td>
<td>7.0325</td>
<td>0.4578</td>
<td>15.36</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="even">
<td><strong>TV</strong></td>
<td>0.0475</td>
<td>0.0027</td>
<td>17.67</td>
<td>&lt; 0.0001</td>
</tr>
</tbody>
</table>
</section>
<section id="assessing-the-overall-accuracy-of-the-model" class="slide level2 center">
<h2>Assessing the Overall Accuracy of the Model</h2>
<div style="font-size: 80%;">
<ul>
<li>Residual Standard Error (RSE):</li>
</ul>
<p><span class="math display">\[
  RSE = \sqrt{\frac{1}{n-2} RSS} = \sqrt{\frac{1}{n-2} \sum_{i=1}^n (y_i - \hat{y}_i)^2}
\]</span> where the Residual Sum of Square (RSS) is <span class="math inline">\(\sum_{i=1}^n (y_i - \hat{y})^2\)</span>.</p>
<div class="fragment">
<ul>
<li><span class="math inline">\(R^2\)</span>, the fraction of variance explained:</li>
</ul>
<p><span class="math display">\[
  R^2 = \frac{TSS - RSS}{TSS} = 1 - \frac{RSS}{TSS}, \quad TSS = \sum_{i=1}^n (y_i - \bar{y})^2
\]</span> where TSS is the Total Sums of Squares.</p>
</div>
<div class="fragment">
<ul>
<li>It can be shown that in this Simple Linear Regression setting that <span class="math inline">\(R^2 = r^2\)</span>, where <span class="math inline">\(r\)</span> is the correlation between X and Y:</li>
</ul>
<p><span class="math display">\[
r = \frac{\sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum_{i=1}^n (x_i - \bar{x})^2 \sum_{i=1}^n (y_i - \bar{y})^2}}
\]</span></p>
</div>
</div>
</section>
<section id="advertising-data-results" class="slide level2 center">
<h2>Advertising Data Results</h2>
<p><br></p>
<p>Key metrics for model accuracy:</p>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Residual Standard Error</td>
<td>3.26</td>
</tr>
<tr class="even">
<td>R²</td>
<td>0.612</td>
</tr>
<tr class="odd">
<td>F-statistic</td>
<td>312.1</td>
</tr>
</tbody>
</table>
<p><br></p>
</section></section>
<section>
<section id="multiple-linear-regression" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Multiple Linear Regression</h1>

</section>
<section id="multiple-linear-regression-1" class="slide level2 center">
<h2>Multiple Linear Regression</h2>
<div style="font-size: 80%;">
<ul>
<li>Here our model is</li>
</ul>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p + \epsilon,
\]</span></p>
<ul>
<li>We interpret <span class="math inline">\(\beta_j\)</span> as the <em>average</em> effect on <span class="math inline">\(Y\)</span> of a one-unit increase in <span class="math inline">\(X_j\)</span>, <em>holding all other predictors fixed</em>.</li>
</ul>
<div class="fragment">
<ul>
<li>In the advertising example, the model becomes</li>
</ul>
<p><span class="math display">\[
\text{sales} = \beta_0 + \beta_1 \times \text{TV} + \beta_2 \times \text{radio} + \beta_3 \times \text{newspaper} + \epsilon.
\]</span></p>
</div>
</div>
</section>
<section id="interpreting-regression-coefficients" class="slide level2 center">
<h2>Interpreting Regression Coefficients</h2>
<ul>
<li class="fragment">The ideal scenario is when the predictors are uncorrelated — a <em>balanced design</em>:
<ul>
<li class="fragment">Each coefficient can be estimated and tested separately.</li>
<li class="fragment">Interpretations such as “<em>a unit change in</em> <span class="math inline">\(X_j\)</span> is associated with a <span class="math inline">\(\beta_j\)</span> change in <span class="math inline">\(Y\)</span>, while all the other variables stay fixed” are possible.</li>
</ul></li>
<li class="fragment">Correlations amongst predictors cause problems:
<ul>
<li class="fragment">The variance of all coefficients tends to increase, sometimes dramatically.</li>
<li class="fragment">Interpretations become hazardous — when <span class="math inline">\(X_j\)</span> changes, everything else changes.</li>
</ul></li>
<li class="fragment"><em>Claims of causality</em> should be avoided for observational data.</li>
</ul>
<!---
## Two Quotes by Famous Statisticians

> "Essentially, all models are wrong, but some are useful."\
> — **George Box**

> "The only way to find out what will happen when a complex system is disturbed is to disturb the system, not merely to observe it passively."\
> — **Fred Mosteller and John Tukey**

--->
</section>
<section id="estimation-and-prediction-for-multiple-regression" class="slide level2 center">
<h2>Estimation and Prediction for Multiple Regression</h2>
<div style="font-size: 80%;">
<ul>
<li>Given estimates <span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \ldots, \hat{\beta}_p\)</span>, we can make predictions using the formula:</li>
</ul>
<p><span class="math display">\[
  \hat{y} = \hat{\beta}_0 + \hat{\beta}_1x_1 + \hat{\beta}_2x_2 + \cdots + \hat{\beta}_px_p.
\]</span></p>
<div class="fragment">
<ul>
<li>We estimate <span class="math inline">\(\beta_0, \beta_1, \ldots, \beta_p\)</span> as the values that minimize the sum of squared residuals:</li>
</ul>
<p><span class="math display">\[
  \text{RSS} = \sum_{i=1}^n \left( y_i - \hat{y}_i \right)^2
             = \sum_{i=1}^n \left( y_i - \hat{\beta}_0 - \hat{\beta}_1x_{i1} - \hat{\beta}_2x_{i2} - \cdots - \hat{\beta}_px_{ip} \right)^2.
\]</span></p>
<ul>
<li>This is done using standard statistical software. The values <span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \ldots, \hat{\beta}_p\)</span> that minimize RSS are the multiple least squares regression coefficient estimates.</li>
</ul>
</div>
</div>
</section>
<section id="section" class="slide level2 center">
<h2></h2>

<img data-src="figs/3_4-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"><p><br></p>
</section>
<section id="results-for-advertising-data" class="slide level2 center">
<h2>Results for Advertising Data</h2>
<div style="font-size: 80%;">
<center>
<strong>Regression Coefficients</strong>
</center>
<table class="caption-top">
<thead>
<tr class="header">
<th>Predictor</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-statistic</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>2.939</td>
<td>0.3119</td>
<td>9.42</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="even">
<td>TV</td>
<td>0.046</td>
<td>0.0014</td>
<td>32.81</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="odd">
<td>radio</td>
<td>0.189</td>
<td>0.0086</td>
<td>21.89</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="even">
<td>newspaper</td>
<td>-0.001</td>
<td>0.0059</td>
<td>-0.18</td>
<td>0.8599</td>
</tr>
</tbody>
</table>

<div class="fragment">
<center>
<strong>Correlations</strong>
</center>
<table class="caption-top">
<thead>
<tr class="header">
<th>Predictor</th>
<th>TV</th>
<th>radio</th>
<th>newspaper</th>
<th>sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>TV</strong></td>
<td>1.0000</td>
<td>0.0548</td>
<td>0.0567</td>
<td>0.7822</td>
</tr>
<tr class="even">
<td><strong>radio</strong></td>
<td></td>
<td>1.0000</td>
<td>0.3541</td>
<td>0.5762</td>
</tr>
<tr class="odd">
<td><strong>newspaper</strong></td>
<td></td>
<td></td>
<td>1.0000</td>
<td>0.2283</td>
</tr>
<tr class="even">
<td><strong>sales</strong></td>
<td></td>
<td></td>
<td></td>
<td>1.0000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="some-important-questions" class="slide level2 center">
<h2>Some Important Questions</h2>
<p><br></p>
<ol type="1">
<li class="fragment"><p>Is at least one of the predictors <span class="math inline">\(X_1, X_2, \dots, X_p\)</span> useful in predicting the response?</p></li>
<li class="fragment"><p>Do all the predictors help to explain <span class="math inline">\(Y\)</span>, or is only a subset of the predictors useful?</p></li>
<li class="fragment"><p>How well does the model fit the data?</p></li>
<li class="fragment"><p>Given a set of predictor values, what response value should we predict, and how accurate is our prediction?</p></li>
</ol>
</section>
<section id="is-at-least-one-predictor-useful" class="slide level2 center">
<h2>Is at Least One Predictor Useful?</h2>
<p>For the first question, we can use the F-statistic:</p>
<p><span class="math display">\[
F = \frac{(TSS - RSS) / p}{RSS / (n - p - 1)} \sim F_{p, n-p-1}
\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Residual Standard Error</td>
<td>1.69</td>
</tr>
<tr class="even">
<td><span class="math inline">\(R^2\)</span></td>
<td>0.897</td>
</tr>
<tr class="odd">
<td>F-statistic</td>
<td>570</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>The F-statistic is huge and it’s p-value is less than <span class="math inline">\(.0001\)</span>. This says that there’s a strong association of the predictors on the outcome variable.</p>
</section></section>
<section>
<section id="deciding-on-the-important-variables" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Deciding on the Important Variables</h1>

</section>
<section id="deciding-on-the-important-variables-1" class="slide level2 center">
<h2>Deciding on the Important Variables</h2>
<ul>
<li class="fragment"><p>The most direct approach is called <strong>all subsets</strong> or <strong>best subsets</strong> regression:</p>
<ul>
<li class="fragment"><p>Compute the least squares fit for all possible subsets.</p></li>
<li class="fragment"><p>Choose between them based on some criterion that balances training error with model size.</p></li>
</ul></li>
</ul>
<div class="fragment">
<ul>
<li class="fragment"><p>However, we often can’t examine all possible models since there are (<span class="math inline">\(2^p\)</span>) of them.</p>
<ul>
<li class="fragment">For example, when (p = 40), there are over a billion models!</li>
</ul></li>
<li class="fragment"><p>Instead, we need an automated approach that searches through a subset of them.</p></li>
</ul>
</div>
</section>
<section id="forward-selection" class="slide level2 center">
<h2>Forward Selection</h2>
<ul>
<li class="fragment"><p>Begin with the <strong>null model</strong> — a model that contains an intercept but no predictors.</p></li>
<li class="fragment"><p>Fit <span class="math inline">\(p\)</span> Simple Linear Regressions and add to the null model the variable that results in the lowest RSS.</p></li>
<li class="fragment"><p>Add to that model the variable that results in the lowest RSS amongst all two-variable models.</p></li>
<li class="fragment"><p>Continue until some stopping rule is satisfied:</p>
<ul>
<li class="fragment">For example, when all remaining variables have a p-value above some threshold.</li>
</ul></li>
</ul>
</section>
<section id="backward-selection" class="slide level2 center">
<h2>Backward Selection</h2>
<ul>
<li class="fragment"><p>Start with all variables in the model.</p></li>
<li class="fragment"><p>Remove the variable with the largest p-value — that is, the variable that is the least statistically significant.</p></li>
<li class="fragment"><p>The new (<span class="math inline">\(p - 1\)</span>)-variable model is fit, and the variable with the largest p-value is removed.</p></li>
<li class="fragment"><p>Continue until a stopping rule is reached:</p>
<ul>
<li class="fragment">For instance, we may stop when all remaining variables have a significant p-value defined by some significance threshold.</li>
</ul></li>
</ul>
</section>
<section id="model-selection" class="slide level2 center">
<h2>Model Selection</h2>
<ul>
<li class="fragment"><p>We will discuss other criterias for choosing an “optimal” member in the path of models produced by forward or backward stepwise selection, including:</p>
<ul>
<li class="fragment"><p>Mallow’s <span class="math inline">\(C_p\)</span></p></li>
<li class="fragment"><p>Akaike information criterion (AIC)</p></li>
<li class="fragment"><p>Bayesian information criterion (BIC)</p></li>
<li class="fragment"><p>Adjusted <span class="math inline">\(R^2\)</span></p></li>
<li class="fragment"><p>Cross-validation (CV)</p></li>
</ul></li>
</ul>
</section></section>
<section>
<section id="other-considerations-in-the-regression-model" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Other Considerations in the Regression Model</h1>

</section>
<section id="qualitative-predictors" class="slide level2 center">
<h2>Qualitative Predictors</h2>
<ul>
<li class="fragment"><p>Some predictors are <strong>qualitative</strong>, taking discrete values.</p></li>
<li class="fragment"><p>Categorical predictors can be represented using <strong>factor variables</strong>.</p></li>
<li class="fragment"><p><strong>Qualitative variables:</strong> Student (Student Status), Status (Marital Status), Own (Owns a House).</p></li>
</ul>
</section>
<section id="credit-card-data" class="slide level2 center">
<h2>Credit Card Data</h2>

<img data-src="figs/3_6-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:75.0%"><p><br></p>
</section>
<section id="credit-card-data-1" class="slide level2 center">
<h2>Credit Card Data</h2>
<p>Suppose we investigate differences in credit card balance between those who own a house and those who do not, ignoring the other variables. We create a new variable:</p>
<p><span class="math display">\[
x_i =
\begin{cases}
1 &amp; \text{if } i\text{th person owns a house} \\
0 &amp; \text{if } i\text{th person does not own a house}
\end{cases}
\]</span></p>
<p>Resulting model:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \epsilon_i =
\begin{cases}
\beta_0 + \beta_1 + \epsilon_i &amp; \text{if } i\text{th person owns a house} \\
\beta_0 + \epsilon_i &amp; \text{if } i\text{th person does not own a house.}
\end{cases}
\]</span></p>
</section>
<section id="credit-card-data-2" class="slide level2 center">
<h2>Credit Card Data</h2>
<center>
<strong>Results for the model:</strong>
</center>
<table class="caption-top">
<thead>
<tr class="header">
<th>Predictor</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-statistic</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>509.80</td>
<td>33.13</td>
<td>15.389</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="even">
<td>Own [Yes]</td>
<td>19.73</td>
<td>46.05</td>
<td>0.429</td>
<td>0.6690</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>We see the coefficient is 19.73, but it’s not significant. The p value is 0.66 which is not significant (&gt; 0.05). So, owing a house don’t generally means a higher credit card balance than not owing one.</p>
<p><br></p>
</section>
<section id="qualitative-predictors-with-more-than-two-levels" class="slide level2 center">
<h2>Qualitative Predictors with More Than Two Levels</h2>
<p><br></p>
<p>With more than two levels, we create additional dummy variables.</p>
<p>For example, for the `region`` variable, we create two dummy variables:</p>
<p><span class="math display">\[
x_{i1} =
\begin{cases}
      1 &amp; \text{if i-th person is from the South} \\
      0 &amp; \text{if i-th person is not from the South}
    \end{cases}
\]</span></p>
<p><span class="math display">\[
x_{i2} = \begin{cases}
      1 &amp; \text{if i-th person is from the West} \\
      0 &amp; \text{if i-th person is not from the West}
    \end{cases}
\]</span></p>
</section>
<section id="qualitative-predictors-1" class="slide level2 center">
<h2>Qualitative Predictors</h2>
<p><br></p>
<p>Both variables can be used in the regression equation to obtain the model:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_{i1} + \beta_2 x_{i2} + \epsilon_i =
\begin{cases}
      \beta_0 + \beta_1 + \epsilon_i &amp; \text{if i-th person is from the South} \\
      \beta_0 + \beta_2 + \epsilon_i &amp; \text{if i-th person is from the West}\\
      \beta_0 + \epsilon_i &amp; \text{if i-th person is from the East (baseline)}
    \end{cases}
\]</span> <br></p>
<p><strong>Note:</strong> There will always be one fewer dummy variable than the number of levels. The level with no dummy variable — East in this example — is known as the baseline.</p>
</section>
<section id="results-for-region" class="slide level2 center">
<h2>Results for Region</h2>
<p><br></p>
<table class="caption-top">
<colgroup>
<col style="width: 31%">
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 18%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-statistic</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>531.00</td>
<td>46.32</td>
<td>11.464</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="even">
<td>region <span class="math inline">\(South\)</span></td>
<td>-18.69</td>
<td>65.02</td>
<td>-0.287</td>
<td>0.7740</td>
</tr>
<tr class="odd">
<td>region <span class="math inline">\(West\)</span></td>
<td>-12.50</td>
<td>56.68</td>
<td>-0.221</td>
<td>0.8260</td>
</tr>
</tbody>
</table>
<p><br></p>
<p>The coefficient -18.69 compares South to East and that’s not significant. Likewise, the West to East is also not significant.</p>
<p><br></p>
<p><strong>Note</strong>: the choice of the baseline does not affect the fit of the model. The residual sum of sum of squares will be the same no matter which category we chose as the baseline. At its turn, the p-values will potentially change as we change the baseline category.</p>
</section></section>
<section>
<section id="extensions-of-the-linear-model" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Extensions of the Linear Model</h1>

</section>
<section id="interactions" class="slide level2 center">
<h2>Interactions</h2>
<p>In our previous analysis of the <strong>Advertising</strong> data, we assumed that the effect on <strong>sales</strong> of increasing one advertising medium is independent of the amount spent on the other media.</p>
<div class="fragment">
<p>For example, the linear model</p>
<p><span class="math display">\[
\widehat{\text{sales}} = \beta_0 + \beta_1 \times \text{TV} + \beta_2 \times \text{radio} + \beta_3 \times \text{newspaper}
\]</span></p>
<p>states that the average effect on <strong>sales</strong> of a one-unit increase in <strong>TV</strong> is always <span class="math inline">\(\beta_1\)</span>, regardless of the amount spent on <strong>radio</strong>.</p>
</div>
</section>
<section id="interactions-1" class="slide level2 center">
<h2>Interactions</h2>
<ul>
<li class="fragment"><p>But suppose that spending money on <strong>radio</strong> advertising actually increases the effectiveness of <strong>TV</strong> advertising, so that the slope term for <strong>TV</strong> should increase as <strong>radio</strong> increases.</p></li>
<li class="fragment"><p>In this situation, given a fixed budget of $100,000, spending half on <strong>radio</strong> and half on <strong>TV</strong> may increase <strong>sales</strong> more than allocating the entire amount to either <strong>TV</strong> or <strong>radio</strong>.</p></li>
<li class="fragment"><p>In marketing, this is known as a <strong>synergy effect</strong>, and in statistics, it is referred to as an <strong>interaction effect</strong>.</p></li>
</ul>
</section>
<section id="interaction-in-advertising-data" class="slide level2 center">
<h2>Interaction in Advertising Data</h2>

<img data-src="figs/3_5-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"><ul>
<li class="fragment"><p>When levels of TV or radio are low, true sales are lower than predicted.</p></li>
<li class="fragment"><p>Splitting advertising between TV and radio underestimates sales.</p></li>
</ul>
<p><br></p>
</section>
<section id="modeling-interactions" class="slide level2 center">
<h2>Modeling Interactions</h2>
<p>Model takes the form:</p>
<p><span class="math display">\[
\text{sales} = \beta_0 + \beta_1 \times \text{TV} + \beta_2 \times \text{radio} + \beta_3 \times (\text{radio} \times \text{TV}) + \epsilon
\]</span></p>
<p><br></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Term</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-statistic</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>6.7502</td>
<td>0.248</td>
<td>27.23</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="even">
<td>TV</td>
<td>0.0191</td>
<td>0.002</td>
<td>12.70</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="odd">
<td>radio</td>
<td>0.0289</td>
<td>0.009</td>
<td>3.24</td>
<td>0.0014</td>
</tr>
<tr class="even">
<td>TV × radio</td>
<td>0.0011</td>
<td>0.000</td>
<td>20.73</td>
<td>&lt; 0.0001</td>
</tr>
</tbody>
</table>
</section>
<section id="interpretation" class="slide level2 center">
<h2>Interpretation</h2>
<ul>
<li class="fragment"><p>The results in this table suggest that interactions are important.The p-value for the interaction term <strong>TV</strong> <span class="math inline">\(\times\)</span> radio is extremely low, indicating that there is strong evidence for ( H_A : <span class="math inline">\(\beta_3 \neq 0\)</span>).</p></li>
<li class="fragment"><p>The ( <span class="math inline">\(R^2\)</span> ) for the interaction model is 96.8%, compared to only 89.7% for the model that predicts <strong>sales</strong> using <strong>TV</strong> and <strong>radio</strong> without an interaction term.</p></li>
<li class="fragment"><p>This means that (<span class="math inline">\(\frac{96.8 - 89.7}{100 - 89.7}\)</span>) = 69% of the variability in <strong>sales</strong> that remains after fitting the additive model has been explained by the interaction term.</p></li>
<li class="fragment"><p>The coefficient estimates in the table suggest that an increase in <strong>TV</strong> advertising of $1,000 is associated with increased sales of (<span class="math inline">\(\hat{\beta}_1 + \hat{\beta}_3 \times \text{radio}\)</span>) <span class="math inline">\(\times 1000 = 19 + 1.1 \times \text{radio} \text{ units}.\)</span></p></li>
<li class="fragment"><p>An increase in <strong>radio</strong> advertising of $1,000 will be associated with an increase in sales of (<span class="math inline">\(\hat{\beta}_2 + \hat{\beta}_3 \times \text{TV}\)</span>) <span class="math inline">\(\times 1000 = 29 + 1.1 \times \text{TV} \text{ units}.\)</span></p></li>
</ul>
</section>
<section id="hierarchy" class="slide level2 center">
<h2>Hierarchy</h2>
<ul>
<li class="fragment"><p>Sometimes it is the case that an interaction term has a very small p-value, but the associated main effects (in this case, <strong>TV</strong> and <strong>radio</strong>) do not.</p></li>
<li class="fragment"><p>The <em>hierarchy principle</em>:</p>
<ul>
<li class="fragment"><em>If we include an interaction in a model, we should also include the main effects, even if the p-values associated with their coefficients are not significant.</em></li>
</ul></li>
<li class="fragment"><p>The rationale for this principle is that interactions are hard to interpret in a model without main effects.</p></li>
<li class="fragment"><p>Specifically, the interaction terms also contain main effects, if the model has no main effect terms.</p></li>
</ul>
</section>
<section id="interactions-between-qualitative-and-quantitative-variables" class="slide level2 center">
<h2>Interactions Between Qualitative and Quantitative Variables</h2>
<p>Consider the <code>Credit</code> data set, and suppose that we wish to predict <code>balance</code> using <code>income</code> (quantitative) and <code>student</code> (qualitative).</p>
<p>Without an interaction term, the model takes the form:</p>
<p><span class="math display">\[
\text{balance}_i \approx \beta_0 + \beta_1 \times \text{income}_i +
\begin{cases}
\beta_2 &amp; \text{if } i^\text{th} \text{ person is a student} \\
0 &amp; \text{if } i^\text{th} \text{ person is not a student}
\end{cases}
\]</span></p>
<p><span class="math display">\[
= \beta_1 \times \text{income}_i +
\begin{cases}
\beta_0 + \beta_2 &amp; \text{if } i^\text{th} \text{ person is a student} \\
\beta_0 &amp; \text{if } i^\text{th} \text{ person is not a student}
\end{cases}
\]</span></p>
</section>
<section id="with-interactions-it-takes-the-form" class="slide level2 center">
<h2>With Interactions, It Takes the Form</h2>
<p><span class="math display">\[
\text{balance}_i \approx \beta_0 + \beta_1 \times \text{income}_i +
\begin{cases}
\beta_2 + \beta_3 \times \text{income}_i &amp; \text{if student} \\
0 &amp; \text{if not student}
\end{cases}
\]</span></p>
<p><span class="math display">\[
=
\begin{cases}
(\beta_0 + \beta_2) + (\beta_1 + \beta_3) \times \text{income}_i &amp; \text{if student} \\
\beta_0 + \beta_1 \times \text{income}_i &amp; \text{if not student}
\end{cases}
\]</span></p>
</section>
<section id="visualizing-interactions" class="slide level2 center">
<h2>Visualizing Interactions</h2>

<img data-src="figs/3_7-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"><ul>
<li class="fragment">Left: no interaction between <code>income</code> and <code>student</code>.</li>
<li class="fragment">Right: with an interaction term between <code>income</code> and <code>student</code>.</li>
</ul>
<p><br></p>
</section></section>
<section>
<section id="non-linear-effects-of-predictors" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Non-linear effects of predictors</h1>

</section>
<section id="non-linear-effects-of-predictors-1" class="slide level2 center">
<h2>Non-linear effects of predictors</h2>
<center>
<strong>Polynomial regression on Auto data</strong>
</center>

<img data-src="figs/3_8-1.png" class="quarto-figure quarto-figure-center r-stretch" style="width:65.0%"></section>
<section id="non-linear-regression-results" class="slide level2 center">
<h2>Non-linear regression results</h2>
<p>The figure suggests that the following model</p>
<p><span class="math display">\[
mpg = \beta_0 + \beta_1 \times horsepower + \beta_2 \times horsepower^2 + \epsilon
\]</span></p>
<p>may provide a better fit.</p>
<table class="caption-top">
<colgroup>
<col style="width: 31%">
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 18%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-statistic</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>56.9001</td>
<td>1.8004</td>
<td>31.6</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="even">
<td>horsepower</td>
<td>-0.4662</td>
<td>0.0311</td>
<td>-15.0</td>
<td>&lt; 0.0001</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\text{horsepower}^2\)</span></td>
<td>0.0012</td>
<td>0.0001</td>
<td>10.1</td>
<td>&lt; 0.0001</td>
</tr>
</tbody>
</table>
</section>
<section id="what-we-did-not-cover" class="slide level2 center">
<h2>What we did not cover</h2>
<ul>
<li>Outliers</li>
<li>Non-constant variance of error terms</li>
<li>High leverage points</li>
<li>Collinearity</li>
</ul>
</section>
<section id="generalizations-of-the-linear-model" class="slide level2 center">
<h2>Generalizations of the Linear Model</h2>
<ul>
<li><p>In much of the rest of the course we discuss methods that expand the scope of linear models and how they are fit:</p>
<ul>
<li><p><strong>Classification problems:</strong> logistic regression, support vector machines.</p></li>
<li><p><strong>Non-linearity:</strong> kernel smoothing, splines, generalized additive models; nearest neighbor methods.</p></li>
<li><p><strong>Interactions:</strong> Tree-based methods, bagging, random forests, boosting (these also capture non-linearities).</p></li>
<li><p><strong>Regularized fitting:</strong> Ridge regression and lasso.</p></li>
</ul></li>
</ul>
</section></section>
<section>
<section id="the-marketing-plan-answers" class="title-slide slide level1 center">
<h1>The Marketing Plan: Answers</h1>

</section>
<section id="the-marketing-plan-answers-1" class="slide level2 center">
<h2>The Marketing Plan: Answers</h2>
<div style="font-size: 80%;">
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>1.Is there a relationship between sales and advertising budget?</strong></p>
<p>Fit a multiple regression of <strong>sales</strong> on <strong>TV</strong>, <strong>radio</strong>, and <strong>newspaper</strong>, and test</p>
<p><span class="math display">\[
H_0:\ \beta_{\text{TV}}=\beta_{\text{radio}}=\beta_{\text{newspaper}}=0.
\]</span></p>
<p>Using the <span class="math inline">\(F\)</span>-statistic, the very small <span class="math inline">\(p\)</span>-value indicates clear evidence of a relationship between advertising and sales.</p>
<div class="fragment">
<p><strong>2. How strong is the relationship?</strong></p>
<p>Two accuracy measures:</p>
<ul>
<li class="fragment"><p><strong>RSE</strong>: estimates the standard deviation of the response from the population regression line. For <em>Advertising</em>, RSE <span class="math inline">\(\approx\)</span> 3.26. In other words, actual sales in each market deviate from the true regression line by approximately 3,260 units, on average. In the data set, the mean value of sales over all markets is approximately 14,000 units, and so the percentage error is 3,260/14,000 = 23 %.</p></li>
<li class="fragment"><p><strong><span class="math inline">\(R^2\)</span></strong> (variance explained): records the percentage of variability in the response that is explained by the predictors. Predictors explain ~90% of the variance in <strong>sales</strong>.</p></li>
</ul>
</div>
</div><div class="column" style="width:50%;">
<div class="fragment">
<p><strong>3. Which media are associated with sales?</strong></p>
<p>Check <span class="math inline">\(p\)</span>-values for each predictor’s <span class="math inline">\(t\)</span>-statistic. The <span class="math inline">\(p\)</span>-values for <strong>TV</strong> and <strong>radio</strong> are low, but <strong>newspaper</strong> is not, suggesting only TV and radio are related to <strong>sales</strong>.</p>
</div>
<div class="fragment">
<p><strong>4. How large is the association between each medium and sales?</strong></p>
<p>We used SEs to build 95% CIs for coefficients related to <strong>TV</strong>, <strong>Radio</strong>, <strong>Newspaper</strong>.</p>
<p>TV and radio intervals are narrow and far from 0, which means a strong evidence of association. Newspaper CI includes 0, not significant given TV and radio.</p>
</div>
<div class="fragment">
<p><strong>5. How accurately can we predict future sales?</strong></p>
<p>Accuracy depends on whether predicting an <strong>individual</strong> response, <span class="math inline">\(Y=f(X)+\epsilon\)</span>, or the <strong>average</strong> response, <span class="math inline">\(f(X)\)</span>.</p>
<ul>
<li class="fragment"><p>Individual <span class="math inline">\(\rightarrow\)</span> <strong>prediction interval</strong></p></li>
<li class="fragment"><p>Average <span class="math inline">\(\rightarrow\)</span> <strong>confidence interval</strong></p></li>
</ul>
<div class="fragment">
<p>Prediction intervals are always wider because they include irreducible error uncertainty from <span class="math inline">\(\epsilon\)</span>.</p>
</div>
</div>
</div></div>
</div>
</section>
<section id="the-marketing-plan-answers-2" class="slide level2 center">
<h2>The Marketing Plan: Answers</h2>
<div class="columns">
<div class="column" style="font-size: 90%;">
<div class="fragment">
<p><strong>6. Is the relationship linear?</strong></p>
<p>Residual plots help diagnose nonlinearity; linear relationships yield residuals with no pattern. Transformations can accommodate nonlinearity within linear regression.</p>
</div>
</div><div class="column" style="font-size: 90%;">
<div class="fragment">
<p><strong>7. Is there synergy among the advertising media?</strong></p>
<p>Standard linear regression assumes <strong>additivity</strong>. This is interpretable but may be unrealistic. An <strong>interaction term</strong> allows non-additive relationships; a small <span class="math inline">\(p\)</span>-value on the interaction indicates synergy. For <em>Advertising</em>, adding an interaction increases <span class="math inline">\(R^2\)</span> substantially — from ~90% to almost <strong>97%</strong>.</p>
</div>
</div></div>
</section></section>
<section>
<section id="summary" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Summary</h1>

</section>
<section id="summary-1" class="slide level2 center">
<h2>Summary</h2>
<div style="font-size: 80%;">
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><p><strong>Linear Regression</strong>:</p>
<ul>
<li>A foundational supervised learning method.</li>
<li>Assumes a linear relationship between predictors (<span class="math inline">\(X\)</span>) and the response (<span class="math inline">\(Y\)</span>).</li>
<li>Useful for both <strong>prediction</strong> and <strong>understanding relationships</strong>.</li>
</ul></li>
<li><p><strong>Simple vs.&nbsp;Multiple Regression</strong>:</p>
<ul>
<li>Simple regression: one predictor.</li>
<li>Multiple regression: multiple predictors.</li>
</ul></li>
<li><p><strong>Key Metrics</strong>:</p>
<ul>
<li>Residual Standard Error (RSE), <span class="math inline">\(R^2\)</span>, and F-statistic.</li>
<li>Confidence intervals and hypothesis testing for coefficients.</li>
</ul></li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><p><strong>Qualitative Predictors</strong>:</p>
<ul>
<li>Use dummy variables for categorical predictors.</li>
<li>Interpret results based on chosen baselines.</li>
</ul></li>
<li><p><strong>Interactions</strong>:</p>
<ul>
<li>Models with interaction terms (e.g., <span class="math inline">\(X_1 \times X_2\)</span>) capture synergistic effects.</li>
</ul></li>
<li><p><strong>Non-linear Effects</strong>:</p>
<ul>
<li>Polynomial regression accounts for curvature in data.</li>
</ul></li>
<li><p><strong>Challenges</strong>:</p>
<ul>
<li>Multicollinearity, outliers, high leverage points.</li>
<li>Overfitting vs.&nbsp;underfitting: balance flexibility and interpretability.</li>
</ul></li>
</ul>
</div></div>
</div>
</section></section>
<section id="thank-you" class="title-slide slide level1 center" data-background-color="#cfb991">
<h1>Thank you!</h1>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Predictive Analytics</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: true,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>